export const archive = [
  {
    id: 1,
    link: "https://www.youtube.com/watch?v=Uf9Sb_Yjdmg",
    titleAz: "Xalqın parlamenti qurulur",
    date: "04.09.2024",
  },
  {
    id: 3,
    link: "#",
    titleAz: "Azxp-nin açılış toplantısı",
    date: "11.01.2025",
  },
  {
    id: 2,
    link: "https://www.youtube.com/watch?v=Wa1JaPV7GEw",
    titleAz: "Xalqın parlamentinin elan günü",
    date: "18.10.2024",
  },
  {
    id: 4,
    link: "https://www.youtube.com/watch?v=46gfXhy2q9E",
    titleAz: "Azxp-nin brinci toplantısı",
    date: "01.01.2025",
  },
  {
    id: 5,
    link: "https://www.youtube.com/watch?v=vushV9NS1R8&t=7693s",
    titleAz: "Azxp-nin ikinci toplantısı",
    date: "18.01.2025",
  },
  {
    id: 6,
    link: "https://www.youtube.com/watch?v=P71erRN-fxA&t=14091s",
    titleAz: "Azxp-nin üçüncü toplantısı",
    date: "25.01.2025",
  },
  {
    id: 7,
    link: "https://www.youtube.com/watch?v=Jda4Erz2J-c",
    titleAz: "Azxp dördüncü toplantısı",
    date: "01.02.2025",
  },
  {
    id: 8,
    link: "https://www.youtube.com/live/ooN9WryX4Ow",
    titleAz: "Azxp beşinci toplantısı",
    date: "09.02.2025",
  },
  {
    id: 9,
    link: "https://www.youtube.com/live/8zmk1Z90YVw",
    titleAz: "Azxp altıncı toplantısı",
    date: "15.02.2025",
  },
  {
    id: 10,
    link: "https://www.youtube.com/watch?v=1iIiun32WJQ",
    titleAz: "Azxp yeddinci toplantısı",
    date: "22.02.2025",
  },
  {
    id: 11,
    link: "https://www.youtube.com/watch?v=Ieat87ZsgqY",
    titleAz: "Azxp səkizinci toplantısı",
    date: "10.03.2025",
  },
  {
    id: 12,
    link: "https://www.youtube.com/watch?v=8Exgs3DZEf0",
    titleAz: "Azxp doqquzuncu toplantısı",
    date: "22.03.2025",
  },
  {
    id: 13,
    link: "https://www.youtube.com/watch?v=l72JVHJ45B8",
    titleAz: "Azxp onuncu toplantısı",
    date: "29.03.2025",
  },
  {
    id: 14,
    link: "https://www.youtube.com/watch?v=ifrpNBFl9Pc",
    titleAz: "Azxp onbrinci toplantısı",
    date: "05.04.2025",
  },
  {
    id: 15,
    link: "https://www.youtube.com/watch?v=9HmztrARs2k",
    titleAz: "Azxp onikinci toplantısı",
    date: "26.04.2025",
  },
  {
    id: 16,
    link: "https://www.youtube.com/watch?v=WbmDxU54fXA",
    titleAz: "AzXP-13 Xocalı soy qrımı",
    date: "26.02.2025",
  },
  {
    id: 17,
    link: "https://www.youtube.com/watch?v=eixixuX8v8U",
    titleAz: "AzXP-14 Tərtər gətliyamı",
    date: "24.05.2025",
  },
  {
    id: 18,
    link: "https://www.youtube.com/watch?v=4WRcEb2uhLc",
    titleAz: "AzXP-15 Tərtər gətliyamı-2",
    date: "07.06.2025",
  },
  {
    id: 19,
    link: "https://www.youtube.com/watch?v=6tRoBTmZmgY",
    titleAz: "AzXP-16 Növbəti iclası",
    date: "14.05.2025",
  },
  {
    id: 20,
    link: "https://www.youtube.com/watch?v=ht_j5BMw0H4",
    titleAz: "AzXP-17 İzrail, iran...",
    date: "21.05.2025",
  },
];
