export const azxpsessions = [
  {
    idn: 1,
    src: "/azxp.jpg",
    textaz: "AzXP elan günü",
    texten: "",
    link: "https://www.youtube.com/watch?v=Wa1JaPV7GEw",
    date: "04.09.2024",
  },
  {
    idn: 2,
    src: "/aba.jpg",
    textaz: "Səs namusdur",
    texten: "",
    link: "https://www.youtube.com/watch?v=sWuKJMCVHg8",
  },
  {
    idn: 3,
    src: "/azxpComing.jpg",
    textaz: "Birləşə bilərik",
    texten: "",
    link: "https://www.youtube.com/watch?v=Uf9Sb_Yjdmg",
  },
  {
    idn: 4,
    src: "/comeTogether.jpg",
    textaz: "AzXP yaranması",
    texten: "",
    link: "https://www.youtube.com/watch?v=5ZVqBN9Cxfs",
  },
  {
    idn: 5,
    src: "/azxpfirst.jpg",
    textaz: "AzXP 1-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=46gfXhy2q9E",
    date: "01.01.2025",
  },
  {
    idn: 6,
    src: "/azxpsecond.jpg",
    textaz: "AzXP 2-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=vushV9NS1R8&t:7693s",
    date: "18.01.2025",
  },
  {
    idn: 7,
    src: "/azxp4.jpg",
    textaz: "AzXP 4-cü iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=Jda4Erz2J-c",
    date: "01.02.2025",
  },
  {
    idn: 8,
    src: "/azxpsessions/azxp5.jpg",
    textaz: "AzXP 5-ci iclası",
    texten: "",
    link: "https://www.youtube.com/live/ooN9WryX4Ow",
    date: "09.02.2025",
  },
  {
    idn: 9,
    src: "/azxpsessions/azxp6.jpg",
    textaz: "AzXP 6-cı iclası",
    texten: "",
    link: "https://www.youtube.com/live/8zmk1Z90YVw",
    date: "15.02.2025",
  },
  {
    idn: 10,
    src: "/azxpsessions/azxp7.jpg",
    textaz: "AzXP 7-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=1iIiun32WJQ",
    date: "22.02.2025",
  },
  {
    idn: 11,
    src: "/azxpsessions/azxp8.jpg",
    textaz: "AzXP 8-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=Ieat87ZsgqY",
    date: "10.03.2025",
  },
  {
    idn: 12,
    src: "/azxpsessions/azxp9.jpg",
    textaz: "AzXP 9-cu iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=8Exgs3DZEf0",
    date: "22.03.2025",
  },
  {
    idn: 13,
    src: "/azxpsessions/azxp10.jpg",
    textaz: "AzXP 10-cu iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=l72JVHJ45B8",
    date: "29.03.2025",
  },
  {
    idn: 14,
    src: "/azxpsessions/azxp11.jpg",
    textaz: "AzXP 11-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=ifrpNBFl9Pc",
    date: "05.04.2025",
  },
  {
    idn: 15,
    src: "/azxpsessions/azxp12.jpg",
    textaz: "AzXP 12-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=9HmztrARs2k",
    date: "26.04.2025",
  },
];
