export const azxpsessions = [
  {
    idn: 1,
    src: "/azxp.jpg",
    textaz: "AzXP elan günü",
    texten: "",
    link: "https://www.youtube.com/watch?v=Wa1JaPV7GEw",
    date: "04.09.2024",
  },
  {
    idn: 2,
    src: "/aba.jpg",
    textaz: "Səs namusdur",
    texten: "",
    link: "https://www.youtube.com/watch?v=sWuKJMCVHg8",
  },
  {
    idn: 3,
    src: "/azxpComing.jpg",
    textaz: "Birləşə bilərik",
    texten: "",
    link: "https://www.youtube.com/watch?v=Uf9Sb_Yjdmg",
  },
  {
    idn: 4,
    src: "/comeTogether.jpg",
    textaz: "AzXP yaranması",
    texten: "",
    link: "https://www.youtube.com/watch?v=5ZVqBN9Cxfs",
  },
  {
    idn: 5,
    src: "/azxpfirst.jpg",
    textaz: "AzXP 1-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=46gfXhy2q9E",
    date: "01.01.2025",
  },
  {
    idn: 6,
    src: "/azxpsecond.jpg",
    textaz: "AzXP 2-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=vushV9NS1R8&t:7693s",
    date: "18.01.2025",
  },
  {
    idn: 7,
    src: "/azxp4.jpg",
    textaz: "AzXP 4-cü iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=Jda4Erz2J-c",
    date: "01.02.2025",
  },
  {
    idn: 8,
    src: "/azxpsessions/azxp5.jpg",
    textaz: "AzXP 5-ci iclası",
    texten: "",
    link: "https://www.youtube.com/live/ooN9WryX4Ow",
    date: "09.02.2025",
  },
  {
    idn: 9,
    src: "/azxpsessions/azxp6.jpg",
    textaz: "AzXP 6-cı iclası",
    texten: "",
    link: "https://www.youtube.com/live/8zmk1Z90YVw",
    date: "15.02.2025",
  },
  {
    idn: 10,
    src: "/azxpsessions/azxp7.jpg",
    textaz: "AzXP 7-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=1iIiun32WJQ",
    date: "22.02.2025",
  },
  {
    idn: 11,
    src: "/azxpsessions/azxp8.jpg",
    textaz: "AzXP 8-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=Ieat87ZsgqY",
    date: "10.03.2025",
  },
  {
    idn: 12,
    src: "/azxpsessions/azxp9.jpg",
    textaz: "AzXP 9-cu iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=8Exgs3DZEf0",
    date: "22.03.2025",
  },
  {
    idn: 13,
    src: "/azxpsessions/azxp10.jpg",
    textaz: "AzXP 10-cu iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=l72JVHJ45B8",
    date: "29.03.2025",
  },
  {
    idn: 14,
    src: "/azxpsessions/azxp11.jpg",
    textaz: "AzXP 11-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=ifrpNBFl9Pc",
    date: "05.04.2025",
  },
  {
    idn: 15,
    src: "/azxpsessions/azxp12.jpg",
    textaz: "AzXP 12-ci iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=9HmztrARs2k",
    date: "26.04.2025",
  },
  {
    idn: 16,
    src: "/azxpsessions/azxp13.jpg",
    textaz: "AzXP-13 Xocalı soy qrımı",
    texten: "x",
    link: "https://www.youtube.com/watch?v=WbmDxU54fXA",
    date: "26.02.2025",
  },
  {
    idn: 17,
    src: "/azxpsessions/azxp14.jpg",
    textaz: "AzXP-14 Tərtər gətliyamı",
    texten: "",
    link: "https://www.youtube.com/watch?v=eixixuX8v8U",
    date: "24.05.2025",
  },
  {
    idn: 18,
    src: "/azxpsessions/azxp15.jpg",
    textaz: "AzXP-15 Tərtər gətliyamı-2",
    texten: "",
    link: "https://www.youtube.com/watch?v=4WRcEb2uhLc",
    date: "07.06.2025",
  },
  {
    idn: 19,
    src: "/azxpsessions/azxp16.jpg",
    textaz: "AzXP-16 Növbəti iclası",
    texten: "",
    link: "https://www.youtube.com/watch?v=6tRoBTmZmgY",
    date: "14.06.2025",
  },
  {
    idn: 20,
    src: "/azxpsessions/azxp17.jpg",
    textaz: "AzXP-17 İzrail, iran...",
    texten: "",
    link: "https://www.youtube.com/watch?v=ht_j5BMw0H4",
    date: "21.06.2025",
  },
  {
    idn: 21,
    src: "/azxpsessions/azxp18.jpg",
    textaz: "AzXP-18 Vacib müzakirə...",
    texten: "",
    link: "https://www.youtube.com/watch?v=9JuhzbwQRas",
    date: "28.06.2025",
  },
  {
    idn: 22,
    src: "/azxpsessions/azxp19.jpg",
    textaz: "AzXP-19 Gündəliyin qəbulu.",
    texten: "",
    link: "https://www.youtube.com/watch?v=0vD834e7-jQ",
    date: "05.07.2025",
  },
  {
    idn: 23,
    src: "/azxpsessions/azxp20.jpg",
    textaz: "AzXP-20 Hakimyəti dalana...",
    texten: "",
    link: "https://www.youtube.com/watch?v=hzYPPkXNMjs",
    date: "12.07.2025",
  },
  {
    idn: 24,
    src: "/azxpsessions/azxp21.jpg",
    textaz: "AzXP-21 Dövlətə təhlükə...",
    texten: "",
    link: "https://www.youtube.com/watch?v=4CuufObKhKA",
    date: "19.07.2025",
  },
  {
    idn: 25,
    src: "/azxpsessions/azxp22.jpg",
    textaz: "AzXP-22 Paşa holding...",
    texten: "",
    link: "https://www.youtube.com/live/htG6TJIBHmU",
    date: "02.08.2025",
  },
  {
    idn: 26,
    src: "/azxpsessions/azxp23.jpg",
    textaz: "AzXP-23 Sülh sazişi...",
    texten: "",
    link: "https://www.youtube.com/live/GJnZiec8b0Y",
    date: "09.08.2025",
  },
  {
    idn: 27,
    src: "/azxpsessions/azxp24.jpg",
    textaz: "AzXP-24 Sərhədlərlə baglı...",
    texten: "",
    link: "https://www.youtube.com/watch?v=ZRRJ6WKy4-o",
    date: "13.09.2025",
  },
  {
    idn: 28,
    src: "/azxpsessions/azxp25.jpg",
    textaz: "AzXP-24 Adnanla baglı...",
    texten: "",
    link: "https://www.youtube.com/live/JYZYU9Aae7w",
    date: "20.09.2025",
  },
  {
    idn: 29,
    src: "/azxpsessions/azxp26.jpg",
    textaz: "AzXP-24 Əliyev ailəsi...",
    texten: "",
    link: "https://www.youtube.com/live/bjo4vvnDkiU",
    date: "27.09.2025",
  },
  {
    idn: 30,
    src: "/azxpsessions/azxp27.jpg",
    textaz: "AzXP-25 Dövlət işgəncələri...",
    texten: "",
    link: "https://www.youtube.com/live/cv-7f7i3h50",
    date: "04.10.2025",
  },
  {
    idn: 31,
    src: "/azxpsessions/azxp28.jpg",
    textaz: "AzXP-26 Qətnamə qəbul edilir...",
    texten: "",
    link: "https://www.youtube.com/live/09tPNSNKZXk",
    date: "11.10.2025",
  },
];
