export const azxpsessions = [
  {
    idn: 1,
    src: "/azxp.jpg",
    textaz: "Azxp elan günü",
    texten: "",
    link: "https://www.youtube.com/watch?v=Wa1JaPV7GEw",
    date: "04.09.2024",
  },
  {
    idn: 2,
    src: "/aba.jpg",
    textaz: "Səs namusdur",
    texten: "",
    link: "https://www.youtube.com/watch?v=sWuKJMCVHg8",
  },
  {
    idn: 3,
    src: "/azxpComing.jpg",
    textaz: "Birləşə bilərik",
    texten: "",
    link: "https://www.youtube.com/watch?v=Uf9Sb_Yjdmg",
  },
  {
    idn: 4,
    src: "/comeTogether.jpg",
    textaz: "Azxp yaranması",
    texten: "",
    link: "https://www.youtube.com/watch?v=5ZVqBN9Cxfs",
  },
  {
    idn: 5,
    src: "/azxpfirst.jpg",
    textaz: "Azxp birinci sessiyası",
    texten: "",
    link: "https://www.youtube.com/watch?v=46gfXhy2q9E",
    date: "01.01.2025",
  },
  {
    idn: 6,
    src: "/azxpsecond.jpg",
    textaz: "Azxp ikinci sessiyası",
    texten: "",
    link: "https://www.youtube.com/watch?v=vushV9NS1R8&t:7693s",
    date: "18.01.2025",
  },
  {
    idn: 7,
    src: "/azxp4.jpg",
    textaz: "Azxp dördüncü sessiyası",
    texten: "",
    link: "https://www.youtube.com/watch?v=Jda4Erz2J-c",
    date: "01.02.2025",
  },
  {
    idn: 8,
    src: "/azxpsessions/azxp5.jpg",
    textaz: "Azxp beşinci sessiyası",
    texten: "",
    link: "https://www.youtube.com/live/ooN9WryX4Ow",
    date: "09.02.2025",
  },
  {
    idn: 9,
    src: "/azxpsessions/azxp6.jpg",
    textaz: "Azxp altıncı sessiyası",
    texten: "",
    link: "https://www.youtube.com/live/8zmk1Z90YVw",
    date: "15.02.2025",
  },
  {
    idn: 10,
    src: "/azxpsessions/azxp7.jpg",
    textaz: "Azxp yeddinci sessiyası",
    texten: "",
    link: "https://www.youtube.com/watch?v=1iIiun32WJQ",
    date: "22.02.2025",
  },
];
