export const candidates = [
  {
    id: 1,
    Adı: "Abid Qafarov Abdin oğlu",
    Təvəllüd: "7/12/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img001.jpg",
    canId: 123,
  },
  {
    id: 2,
    Adı: "Aygün Ələsgərova Sabir qızı",
    Təvəllüd: "1/20/1972",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Müəllimə",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, S-Pq",
    img: "/candidates/img002.jpg",
    canId: 46,
  },
  {
    id: 3,
    Adı: "Cavanşir Xanlarov Məmməd oğlu",
    Təvəllüd: "3/1/1967",
    DogYer: "Bərdə",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Almaniya",
    img: "/candidates/img003.jpg",
    canId: 165,
  },
  {
    id: 4,
    Adı: "Eldar Həmidov Soltanhəmid oğlu",
    Təvəllüd: "4/3/1958",
    DogYer: "Ucar",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "İnşaat",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Musavat",
    Ölkəsi: "Almaniya",
    img: "/candidates/img004.jpg",
    canId: 65,
  },
  {
    id: 5,
    Adı: "Əli Kərimov Bəxtiyar oğlu",
    Təvəllüd: "6/1/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img005.jpg",
    canId: 87,
  },
  {
    id: 6,
    Adı: "Əli Quliyev Əhməd oğlu",
    Təvəllüd: "5/20/1962",
    DogYer: "Qubadlı",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Vətəndaşlıq: "Ukraina",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Ukrayna",
    img: "/candidates/img006.jpg",
    canId: 132,
  },
  {
    id: 7,
    Adı: "Əlövsət Sadıqlı Əhəd oğlu",
    Təvəllüd: "2/3/1953",
    DogYer: "Ağdam",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img007.jpg",
    canId: 143,
  },
  {
    id: 8,
    Adı: "Ənvər Ağamalızadə Yusif oğlu",
    Təvəllüd: "4/2/1953",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "Şair",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img008.jpg",
    canId: 11,
  },
  {
    id: 9,
    Adı: "Faiq Kazımov Oruc oğlu",
    Təvəllüd: "12/29/1960",
    DogYer: "Şəmkir",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AĞ-Partiya",
    Ölkəsi: "Rusiya",
    img: "/candidates/img009.jpg",
    canId: 84,
  },
  {
    id: 10,
    Adı: "Frizman Bağırov Cavad oğlu",
    Təvəllüd: "12/21/1983",
    DogYer: "Göy-göl",
    Təhsil: "Ali",
    İxtisas: "Psixoloq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Gürcüstan, Tiflis",
    img: "/candidates/img010.jpg",
    canId: 17,
  },
  {
    id: 11,
    Adı: "Fuad Mahmudov Əbülfət oğlu",
    Təvəllüd: "7/26/1976",
    DogYer: "Mingəçevir",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Sahibkar",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    Ölkəsi: "Rusiya",
    img: "/candidates/img011.jpg",
    canId: 90,
  },
  {
    id: 12,
    Adı: "Həsrət Telliyev Zeynal oğlu",
    Təvəllüd: "4/18/1960",
    DogYer: "Bəlakən",
    Təhsil: "Orta ",
    İxtisas: "İncəsənət",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bəlakən",
    img: "/candidates/img012.jpg",
    canId: 159,
  },
  {
    id: 13,
    Adı: "İlqar Budaqov Namaz oğlu",
    Təvəllüd: "3/25/1969",
    DogYer: "Beyləqan",
    Təhsil: "Orta",
    İxtisas: "İşsiz",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Beyləqan",
    img: "/candidates/img013.jpg",
    canId: 24,
  },
  {
    id: 14,
    Adı: "İlqar Hüseynli Bəxtiyar oğlu",
    Təvəllüd: "2/4/1990",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İqtisadiyyat",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya ",
    img: "/candidates/img014.jpg",
    canId: 75,
  },
  {
    id: 15,
    Adı: "İqbal Məmmədli İman oğlu",
    Təvəllüd: "11/10/1959",
    DogYer: "Lənkəran",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Lənkəran",
    img: "/candidates/img015.jpg",
    canId: 96,
  },
  {
    id: 16,
    Adı: "İsa Sadıqov Nəzər oğlu",
    Təvəllüd: "6/24/1958",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Hərbçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Norveç",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Norveç",
    img: "/candidates/img016.jpg",
    canId: 145,
  },
  {
    id: 17,
    Adı: "Kəmalə Məmmədova Seydi qızı",
    Təvəllüd: "3/22/1977",
    DogYer: "Şəki",
    Təhsil: "Orta",
    İxtisas: "Tibb bacısı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Rusiya, Krasnoyarsk",
    img: "/candidates/img017.jpg",
    canId: 104,
  },
  {
    id: 18,
    Adı: "Mübariz İsmayılov İsaq oğlu",
    Təvəllüd: "4/3/1966",
    DogYer: "Zaqatala",
    Təhsil: "Ali",
    İxtisas: "Zoomühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Zaqatala",
    img: "/candidates/img018.jpg",
    canId: 82,
  },
  {
    id: 19,
    Adı: "Müşviq Əhmədli Seymur oğlu",
    Təvəllüd: "11/12/1990",
    DogYer: "Bərdə",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bərdə",
    img: "/candidates/img019.jpg",
    canId: 36,
  },
  {
    id: 20,
    Adı: "Natiq Məmmədov Aydın oğlu",
    Təvəllüd: "3/20/1974",
    DogYer: "Naxçıvan",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img020.jpg",
    canId: 99,
  },
  {
    id: 21,
    Adı: "Nurəddin Bayramov Məcid oğlu",
    Təvəllüd: "11/30/1958",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Naxçıvan",
    img: "/candidates/img021.jpg",
    canId: 21,
  },
  {
    id: 22,
    Adı: "Oqtay İskəndərli İskəndər oğlu",
    Təvəllüd: "2/3/1959",
    DogYer: "Göyçay",
    Təhsil: "Ali",
    İxtisas: "iqtisadçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Fransa",
    img: "/candidates/img022.jpg",
    canId: 81,
  },
  {
    id: 23,
    Adı: "Qurban Məmmədov Cəlal oğlu",
    Təvəllüd: "4/2/1959",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İngiltərə",
    img: "/candidates/img023.jpg",
    canId: 100,
  },
  {
    id: 24,
    Adı: "Ramiz Orucov Məcid oğlu",
    Təvəllüd: "5/1/1952",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Fizik",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Gəncə",
    img: "/candidates/img024.jpg",
    canId: 121,
  },
  {
    id: 25,
    Adı: "Razim Kərimov Əyyub oğlu",
    Təvəllüd: "9/24/1972",
    DogYer: "Neftçala",
    Təhsil: "Orta",
    İxtisas: "Ev ustası",
    Fəaliyyət: "Ev ustası",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img025.jpg",
    canId: 88,
  },
  {
    id: 26,
    Adı: "Rəhim Mirzəyev Mirzəağa oğlu",
    Təvəllüd: "4/28/1970",
    DogYer: "Masallı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Almaniya",
    img: "/candidates/img026.jpg",
    canId: 109,
  },
  {
    id: 27,
    Adı: "Rəşad Dadaşov Rufiq oğlu",
    Təvəllüd: "3/29/1983",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img027.jpg",
    canId: 34,
  },
  {
    id: 28,
    Adı: "Rövşən Qəmbər Yunis oğlu",
    Təvəllüd: "6/3/1951",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img028.jpg",
    canId: 129,
  },
  {
    id: 29,
    Adı: "Rza Səfərsoy Əli oğlu",
    Təvəllüd: "5/6/1976",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Hərbi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img029.jpg",
    canId: 150,
  },
  {
    id: 30,
    Adı: "Sadiq Xankişiyev Nahdəli oğlu",
    Təvəllüd: "12/7/1963",
    DogYer: "Sabirabad",
    Təhsil: "Ali",
    Fəaliyyət: "Biznes",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Rusiya",
    img: "/candidates/img030.jpg",
    canId: 163,
  },
  {
    id: 31,
    Adı: "Sahib Məmməd Camal oğlu",
    Təvəllüd: "12/20/1958",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Ədəbiyyat",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Gədəbəy",
    img: "/candidates/img031.jpg",
    canId: 93,
  },
  {
    id: 32,
    Adı: "Sədaqət Paşayeva Saday qızı",
    Təvəllüd: "2/1/1972",
    DogYer: "Ağdam",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Türkiyə",
    img: "/candidates/img032.jpg",
    canId: 122,
  },
  {
    id: 33,
    Adı: "Sərvan Kərimov İdris oğlu",
    Təvəllüd: "6/20/1958",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img033.jpg",
    canId: 89,
  },
  {
    id: 34,
    Adı: "Sevil Muradova Mehbalı qızı",
    Təvəllüd: "1/5/1958",
    DogYer: "Bakı",
    Təhsil: "Orta",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img034.jpg",
    canId: 112,
  },
  {
    id: 35,
    Adı: "Süleyman Məmmədhüseynov Qoca oğlu ",
    Təvəllüd: "4/23/1967",
    DogYer: "Ağdaş",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Ağdaş",
    img: "/candidates/img035.jpg",
    canId: 94,
  },
  {
    id: 36,
    Adı: "Telman Ələkbərsoy Zaman oğlu",
    Təvəllüd: "10/25/1945",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbayan, Gədəbəy",
    img: "/candidates/img036.jpg",
    canId: 45,
  },
  {
    id: 37,
    Adı: "Telman Verdiyev Salman oğlu",
    Təvəllüd: "5/29/1956",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İsveç",
    img: "/candidates/img037.jpg",
    canId: 162,
  },
  {
    id: 38,
    Adı: "Təranə Səfərsoy Həsən qızı",
    Təvəllüd: "7/1/1970",
    DogYer: "Cəbrayıl",
    Təhsil: "Ali",
    İxtisas: "Əmtəəşünas",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img038.jpg",
    canId: 151,
  },
  {
    id: 39,
    Adı: "Teymur Eminbəyli Nəbi oğlu",
    Təvəllüd: "3/3/1960",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İsveç",
    img: "/candidates/img039.jpg",
    canId: 53,
  },
  {
    id: 40,
    Adı: "Tofiq Nüsrətov Yəhya oğlu",
    Təvəllüd: "5/13/1954",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, Moskva",
    img: "/candidates/img040.jpg",
    canId: 118,
  },
  {
    id: 41,
    Adı: "Ülvi Namazlı Arif oğlu",
    Təvəllüd: "9/25/1974",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan,Qazax",
    img: "/candidates/img041.jpg",
    canId: 114,
  },
  {
    id: 42,
    Adı: "Valeh Əliyev Hümmət oğlu",
    Təvəllüd: "9/13/1954",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Müsavat",
    Ölkəsi: "Azərbaycan, Salyan",
    img: "/candidates/img042.jpg",
    canId: 51,
  },
  {
    id: 43,
    Adı: "Vaqif Əhmədov Qasım oğlu",
    Təvəllüd: "1/4/1959",
    DogYer: "Tovuz",
    Təhsil: "Ali",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Tovuz",
    img: "/candidates/img043.jpg",
    canId: 39,
  },
  {
    id: 44,
    Adı: "Vüsal Ələkbərov Tofiq oğlu",
    Təvəllüd: "11/10/1972",
    DogYer: "Gəncə",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Gəncə",
    img: "/candidates/img044.jpg",
    canId: 44,
  },
  {
    id: 45,
    Adı: "Xankişi Həsənov Nəcəf oğlu",
    Təvəllüd: "2/29/1964",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "Təhsil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img045.jpg",
    canId: 69,
  },
  {
    id: 46,
    Adı: "Xatirə Cəbrayılova Sabir qızı",
    Təvəllüd: "12/23/1988",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Kimya",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, Moskva",
    img: "/candidates/img046.jpg",
    canId: 30,
  },
  {
    id: 47,
    Adı: "Xatirə Rəhimli Əziz qızı",
    Təvəllüd: "5/25/1964",
    DogYer: "Ağsu",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img047.jpg",
    canId: 137,
  },
  {
    id: 48,
    Adı: "Zakir Hüseyinov Səfxan oğlu",
    Təvəllüd: "2/3/1958",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Aqronom",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Fizuli",
    img: "/candidates/img048.jpg",
    canId: 73,
  },
  {
    id: 49,
    Adı: "Zirəddin Abdullayev Sayad oğlu",
    Təvəllüd: "6/1/1947",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Filoloq",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Gəncə",
    img: "/candidates/img049.jpg",
    canId: 7,
  },
  {
    id: 50,
    Adı: "Validə Əhmədova Gəncəli qızı",
    Təvəllüd: "5/22/1967",
    DogYer: "Laçın ",
    Təhsil: "Orta",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bərdə",
    img: "/candidates/img050.jpg",
    canId: 42,
  },
  {
    id: 51,
    Adı: "Ruslan Fərzəliyev Sədrəddin oğlu",
    Təvəllüd: "6/11/1990",
    DogYer: "Sabirabad",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Şirvan",
    img: "/candidates/img051.jpg",
    canId: 60,
  },
  {
    id: 52,
    Adı: "Səriyyə Qəmbərova Nurəddin qızı",
    Təvəllüd: "9/23/1985",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Naxçıvan",
    img: "/candidates/img052.jpg",
    canId: 130,
  },
  {
    id: 53,
    Adı: "Vidadi Əhmədov Feyruz oğlu",
    Təvəllüd: "28/03/1956",
    DogYer: "Ucar",
    Təhsil: "Orta",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AzerFreedom",
    Ölkəsi: "Rusiya, N.Novqorod",
    img: "/candidates/img053.jpg",
    canId: 40,
  },
  {
    id: 54,
    Adı: "Elxan Yusifov Oruc oğlu",
    Təvəllüd: "12/31/1950",
    DogYer: "Daşkəsən",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Daşkəsən",
    img: "/candidates/img054.jpg",
    canId: 171,
  },
  {
    id: 55,
    Adı: "Tofiq Məmmədov Şirzad oğlu",
    Təvəllüd: "12/30/1978",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Y. Zelandiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "İnşaatçılar partiyası",
    Ölkəsi: "Y. Zelandiya",
    img: "/candidates/img055.jpg",
    canId: 103,
  },
  {
    id: 56,
    Adı: "Fərid Salmanov İlqar oğlu",
    Təvəllüd: "5/7/1976",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya, Moskva",
    img: "/candidates/img056.jpg",
    canId: 146,
  },
  {
    id: 57,
    Adı: "Anar Mirzəyev Nizam oğlu",
    Təvəllüd: "6/26/1978",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Lənkəran",
    img: "/candidates/img057.jpg",
    canId: 107,
  },
  {
    id: 58,
    Adı: "Namizəd Səfərov Heydər oğlu",
    Təvəllüd: "1/10/1955",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img058.jpg",
    canId: 149,
  },
  {
    id: 59,
    Adı: "Şahəddin Eyvazov Mayıl oğlu",
    Təvəllüd: "11/23/1960",
    DogYer: "Şəmkir",
    Təhsil: "Ali",
    İxtisas: "İncəsənət",
    Fəaliyyət: "Jurnalist",
    Vətəndaşlıq: "Fransa",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Fransa",
    img: "/candidates/img059.jpg",
    canId: 56,
  },
  {
    id: 60,
    Adı: "Şahin İsmayılov Nurəddin oğlu",
    Təvəllüd: "6/9/1958",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İncəsənət",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Ukrayna",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "ASDP",
    Ölkəsi: "Ukrayna",
    img: "/candidates/img060.jpg",
    canId: 83,
  },
  {
    id: 61,
    Adı: "Qələndər Aslanov Məhəmmədəli oğlu",
    Təvəllüd: "6/21/1963",
    DogYer: "Goranboy",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan, Goranboy",
    img: "/candidates/img061.jpg",
    canId: 14,
  },
  {
    id: 62,
    Adı: "Əvəz Məmmədov Musa oğlu",
    Təvəllüd: "10/14/1970",
    DogYer: "Ordubad",
    Təhsil: "Ali",
    İxtisas: "İdman",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Ordubad",
    img: "/candidates/img062.jpg",
    canId: 98,
  },
  {
    id: 63,
    Adı: "Didar Əhmədov Səbzulla oğlu",
    Təvəllüd: "6/2/1955",
    DogYer: "Qusar",
    Təhsil: "Ali",
    İxtisas: "İngilis",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Qusar",
    img: "/candidates/img063.jpg",
    canId: 37,
  },
  {
    id: 64,
    Adı: "Aliyə Eyvazova Musa qızı",
    Təvəllüd: "3/27/1955",
    DogYer: "Yevlax",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Yevlax",
    img: "/candidates/img064.jpg",
    canId: 57,
  },
  {
    id: 65,
    Adı: "Qoşqar Movlayev Ənvər oğlu",
    Təvəllüd: "1/3/1980",
    DogYer: "Ermənistan, Ağbaba",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Ssenarist",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img065.jpg",
    canId: 110,
  },
  {
    id: 66,
    Adı: "Aydın Ələkbərov İsaq oğlu",
    Təvəllüd: "7/29/1956",
    DogYer: "Yevlax",
    Təhsil: "Ali",
    İxtisas: "Tarix-psixologiya",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Müsavat",
    Ölkəsi: "Azərbaycan, Yevlax",
    img: "/candidates/img066.jpg",
    canId: 43,
  },
  {
    id: 67,
    Adı: "Ataxan Əbilov Vəli oğlu",
    Təvəllüd: "6/29/1965",
    DogYer: "Azərbaycan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Hollandiya",
    img: "/candidates/img067.jpg",
    canId: 35,
  },
  {
    id: 68,
    Adı: "Rüstəm Abdullayev Elman oğlu",
    Təvəllüd: "9/14/1988",
    DogYer: "Ağdam",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Ağdam",
    img: "/candidates/img068.jpg",
    canId: 5,
  },
  {
    id: 69,
    Adı: "İsmayıl Abdullayev Mirbala oğlu ",
    Təvəllüd: "11/27/1973",
    DogYer: "Salyan",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Salyan",
    img: "/candidates/img069.jpg",
    canId: 4,
  },
  {
    id: 70,
    Adı: "İlham Bayramov Eldar oğlu",
    Təvəllüd: "8/5/1967",
    DogYer: "Gürcüstan",
    Təhsil: "Orta",
    Fəaliyyət: "Fəhlə",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Zaqatala",
    img: "/candidates/img070.jpg",
    canId: 20,
  },
  {
    id: 71,
    Adı: "Əfqan Ramazanov Aleksandr oğlu",
    Təvəllüd: "7/26/1979",
    DogYer: "Xaçmaz",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Xaçmaz",
    img: "/candidates/img071.jpg",
    canId: 135,
  },
  {
    id: 72,
    Adı: "Ağaxan Abuşov Əlixas oğlu",
    Təvəllüd: "6/24/1965",
    DogYer: "Masallı",
    Təhsil: "Ali",
    İxtisas: "Din",
    Fəaliyyət: "İslam",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya",
    img: "/candidates/img072.jpg",
    canId: 9,
  },
  {
    id: 73,
    Adı: "Sultani Rzayev Orucəliyeviç",
    Təvəllüd: "2/3/1964",
    DogYer: "Astara",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Biznes",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya",
    img: "/candidates/img073.jpg",
    canId: 141,
  },
  {
    id: 74,
    Adı: "Ziyafət Abbasova Teymur qızı",
    Təvəllüd: "10/14/1972",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img074.jpg",
    canId: 3,
  },
  {
    id: 75,
    Adı: "Məkisəd Mirzəyev Arif oğlu",
    Təvəllüd: "1/3/1967",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Aqranom",
    Fəaliyyət: "Siyasət",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "KXCP",
    Ölkəsi: "Azərbaycan, Qazax",
    img: "/candidates/img075.jpg",
    canId: 108,
  },
  {
    id: 76,
    Adı: "Əli Bədəlov Mustafa oğlu",
    Təvəllüd: "3/20/1971",
    DogYer: "Salyan",
    Təhsil: "Orta",
    İxtisas: "İnşaatçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Salyan",
    img: "/candidates/img076.jpg",
    canId: 22,
  },
  {
    id: 77,
    Adı: "Aslan Nəsibov Eldar oğlu",
    Təvəllüd: "12/31/1968",
    DogYer: "Gəncə",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Gəncə",
    img: "/candidates/img077.jpg",
    canId: 117,
  },
  {
    id: 78,
    Adı: "Kamran Ağayev Kamil oğlu",
    Təvəllüd: "7/10/1987",
    DogYer: "Cəlilabad",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Cəlilabad",
    img: "/candidates/img078.jpg",
    canId: 13,
  },
  {
    id: 79,
    Adı: "Fikrət Qəhrəmanov Əliqulu oğlu",
    Təvəllüd: "10/1/1969",
    DogYer: "Şabran",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Şabran",
    img: "/candidates/img079.jpg",
    canId: 128,
  },
  {
    id: 80,
    Adı: "Cəmil Hacıyev Malik oğlu",
    Təvəllüd: "4/8/1977",
    DogYer: "Bakı",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img080.jpg",
    canId: 62,
  },
  {
    id: 81,
    Adı: "Camal Bağırzadə Ramazan oğlu",
    Təvəllüd: "4/8/1957",
    DogYer: "Lənkaran",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img081.jpg",
    canId: 18,
  },
  {
    id: 82,
    Adı: "Faiq Əliyev Məşədi oğlu",
    Təvəllüd: "3/14/1951",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Qazax",
    img: "/candidates/img082.jpg",
    canId: 48,
  },
  {
    id: 83,
    Adı: "Şapur Qasimi Hüseyinqulu oğlu",
    Təvəllüd: "12/31/1946",
    DogYer: "Güney Azərbaycan",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img083.jpg",
    canId: 125,
  },
  {
    id: 84,
    Adı: "Əzimbəy Hüseyinov Hümbət oğlu",
    Təvəllüd: "11/26/1967",
    DogYer: "Ermənistan",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img084.jpg",
    canId: 72,
  },
  {
    id: 85,
    Adı: "Əhmədağa Nərimanov Hacıbala oğlu",
    Təvəllüd: "5/15/1953",
    DogYer: "Saatlı",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Saatlı",
    img: "/candidates/img085.jpg",
    canId: 116,
  },
  {
    id: 86,
    Adı: "Vaqif Xankişiyev Tahir oğlu",
    Təvəllüd: "3/8/1978",
    DogYer: "Sabirabad",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Sabirabad",
    img: "/candidates/img086.jpg",
    canId: 164,
  },
  {
    id: 87,
    Adı: "Elmar Bayramov Bəynişan oğlu",
    Təvəllüd: "3/28/1978",
    DogYer: "Daşkəsən",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Rusiya, Moskva",
    img: "/candidates/img087.jpg",
    canId: 19,
  },
  {
    id: 88,
    Adı: "Ramiz Tağıyev Yusif oğlu",
    Təvəllüd: "6/8/1957",
    DogYer: "Bəlakən",
    Təhsil: "Ali",
    İxtisas: "Tarix",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan ",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img088.jpg",
  },
  {
    id: 89,
    Adı: "Bilal Şirinov Mollaəli oğlu",
    Təvəllüd: "3/12/1956",
    DogYer: "Bəlakən",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan, Bəlakən",
    img: "/candidates/img089.jpg",
    canId: 154,
  },
  {
    id: 90,
    Adı: "Fərid Qəribov Murad oğlu",
    Təvəllüd: "4/21/1986",
    DogYer: "Qəbələ",
    Təhsil: "Ali",
    İxtisas: "Hərbiçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Kanada",
    img: "/candidates/img090.jpg",
    canId: 131,
  },
  {
    id: 91,
    Adı: "Qibləli Fərəcov Əli oğlu",
    Təvəllüd: "9/6/1959",
    DogYer: "Zərdab",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Zərdab",
    img: "/candidates/img091.jpg",
    canId: 59,
  },
  {
    id: 92,
    Adı: "Əlisurət Cavadov Calal oğlu",
    Təvəllüd: "1/28/1955",
    DogYer: "Ağdaş",
    Təhsil: "Orta",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Ağdaş",
    img: "/candidates/img092.jpg",
    canId: 29,
  },
  {
    id: 93,
    Adı: "Elşad Şükürov Nəriman oğlu",
    Təvəllüd: "9/1/1981",
    DogYer: "Cəbrayıl",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Cəbrayıl",
    img: "/candidates/img093.jpg",
    canId: 156,
  },
  {
    id: 94,
    Adı: "Əkbər Cavadov Əsgər oğlu",
    Təvəllüd: "2/1/1958",
    DogYer: "Ağcabədi",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Ağcabədi",
    img: "/candidates/img094.jpg",
    canId: 28,
  },
  {
    id: 95,
    Adı: "Mirqafur Seyidi Mirsədrəddin oğlu",
    Təvəllüd: "8/24/1955",
    DogYer: "Naftalan",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Naftalan",
    img: "/candidates/img095.jpg",
    canId: 152,
  },
  {
    id: 96,
    Adı: "Babək Hüseynli Əsgərağa oğlu",
    Təvəllüd: "11/9/1981",
    DogYer: "Cəlilabad",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Cəlilabad",
    img: "/candidates/img096.jpg",
    canId: 74,
  },
  {
    id: 97,
    Adı: "Həmid Həmidov Razim oğlu",
    Təvəllüd: "10/16/1988",
    DogYer: "Tovuz",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Tovuz",
    img: "/candidates/img097.jpg",
    canId: 66,
  },
  {
    id: 98,
    Adı: "Ağası Məmmədli Baba oğlu",
    Təvəllüd: "4/8/1958",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Moldova",
    img: "/candidates/img098.jpg",
    canId: 95,
  },
  {
    id: 99,
    Adı: "Yaşar Rəsulov Rəsul oğlu",
    Təvəllüd: "9/20/1963",
    DogYer: "Şəki",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Şəki",
    img: "/candidates/img099.jpg",
    canId: 140,
  },
  {
    id: 100,
    Adı: "İlqar Quliyev May oğlu ",
    Təvəllüd: "1/1/1964",
    DogYer: "Kürdəmir",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Kürdəmir",
    img: "/candidates/img100.jpg",
    canId: 133,
  },
  {
    id: 101,
    Adı: "Arzuman Xasməmmədli Yunis oğlu",
    Təvəllüd: "1/21/1957",
    DogYer: "Qazax",
    Təhsil: "Ali",
    Fəaliyyət: "Bələdiyə",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Qazax",
    img: "/candidates/img101.jpg",
    canId: 167,
  },
  {
    id: 102,
    Adı: "Aslan Mehtiyev Nazim oğlu",
    Təvəllüd: "1/14/1985",
    DogYer: "Rustavi ",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Almaniya",
    img: "/candidates/img102.jpg",
    canId: 92,
  },
  {
    id: 103,
    Adı: "Sahib Kərimli Fərman oğlu",
    Təvəllüd: "5/26/1974",
    DogYer: "Şəki",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Şəki",
    img: "/candidates/img103.jpg",
    canId: 86,
  },
  {
    id: 104,
    Adı: "Hüseyn Mustafayev Sahib oğlu",
    Təvəllüd: "2/25/1990",
    DogYer: "Bərdə",
    Təhsil: "Orta",
    İxtisas: "Müsiqi",
    Fəaliyyət: "İncəsənət",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Bərdə",
    img: "/candidates/img104.jpg",
    canId: 113,
  },
  {
    id: 105,
    Adı: "Fariz Şarifov Məhəmmədəli oğlu",
    Təvəllüd: "12/22/1957",
    DogYer: "Ağdaş",
    Təhsil: "Ali",
    İxtisas: "İdamançı",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Ağdaş",
    img: "/candidates/img105.jpg",
    canId: 147,
  },
  {
    id: 106,
    Adı: "Oruc Yusifov İbrahim oölu",
    Təvəllüd: "1/22/1962",
    DogYer: "Ağstafa",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Vətəndaşlıq: "Ukrayna",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    Ölkəsi: "Ukrayna,Kiyev",
    img: "/candidates/img106.jpg",
    canId: 172,
  },
  {
    id: 107,
    Adı: "Tural Sadıqlı Əlövsət oğlu",
    Təvəllüd: "6/10/1984",
    DogYer: "Ağdam",
    Təhsil: "Ali",
    İxtisas: "Şərqşünas",
    Fəaliyyət: "Siyasətşi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Almaniya",
    img: "/candidates/img107.jpg",
    canId: 144,
  },
  {
    id: 108,
    Adı: "Ülviyyə Hüseynova Nağı qızı",
    Təvəllüd: "12/11/1977",
    DogYer: "Kürdəmir",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Türkiyə",
    img: "/candidates/img108.jpg",
    canId: 77,
  },
  {
    id: 109,
    Adı: "Famil Bağırov Zaidağa oğlu",
    Təvəllüd: "2/15/1985",
    DogYer: "Astara",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img109.jpg",
    canId: 16,
  },
  {
    id: 110,
    Adı: "Ravil Həsənov Adil oğlu",
    Təvəllüd: "8/16/1988",
    DogYer: "Xaçmaz",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img110.jpg",
    canId: 68,
  },
  {
    id: 111,
    Adı: "İlham Zahirzadə Zaman oğlu",
    Təvəllüd: "1/27/1965",
    DogYer: "Şərur",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Ukrayna",
    img: "/candidates/img111.jpg",
    canId: 173,
  },
  {
    id: 112,
    Adı: "Ənvər Rəhimov Cəlil oğlu",
    Təvəllüd: "12/24/1966",
    DogYer: "Culfa",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya,Smolensk",
    img: "/candidates/img112.jpg",
    canId: 138,
  },
  {
    id: 113,
    Adı: "Elxan Cəfərov Əhməd oğlu",
    Təvəllüd: "1/8/1987",
    DogYer: "Ordubad",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, N. Çelnı",
    img: "/candidates/img113.jpg",
    canId: 31,
  },
  {
    id: 114,
    Adı: "İlqar Əsgərov Eldar oğlu",
    Təvəllüd: 1964,
    DogYer: "Naxçıvan",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Ukrayna, Vinnitsa",
    img: "/candidates/img114.jpg",
    canId: 54,
  },
  {
    id: 115,
    Adı: "Əziz Əzizov Məhəmməd oğlu",
    Təvəllüd: "7/18/1971",
    DogYer: "Şirvan",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almainiya",
    img: "/candidates/img115.jpg",
    canId: 58,
  },
  {
    id: 116,
    Adı: "Nicat Umuxanlı Telman oğlu",
    Təvəllüd: "10/1/1991",
    DogYer: "Bakı",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Hollandiya",
    img: "/candidates/img116.jpg",
    canId: 161,
  },
  {
    id: 117,
    Adı: "Röya Rəfiyeva Tahir qızı",
    Təvəllüd: "7/3/1981",
    DogYer: "Oguz",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img117.jpg",
    canId: 136,
  },
  {
    id: 118,
    Adı: "Nurlana Xəlilova Xəlil qızı",
    Təvəllüd: "10/11/1978",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaican, Bakı",
    img: "/candidates/img118.jpg",
    canId: 170,
  },
  {
    id: 119,
    Adı: "Nüsrət Həsrətli Həsrət oğlu",
    Təvəllüd: "10/10/1954",
    DogYer: "Agdaş",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "Həkim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AMMN",
    Ölkəsi: "Azərbaican, Agdaş",
    img: "/candidates/img119.jpg",
    canId: 71,
  },
  {
    id: 120,
    Adı: "Şəmsəddin Camiyev Qurbət oğlu",
    Təvəllüd: "12/6/1957",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "İnşaatçı",
    Fəaliyyət: "Həkim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AMMN",
    Ölkəsi: "İsveç",
    img: "/candidates/img120.jpg",
    canId: 27,
  },
  {
    id: 121,
    Adı: "Marif Ağaməmmədov Ayaz oğlu",
    Təvəllüd: "9/15/1966",
    DogYer: "Agsu",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Alamaniya",
    img: "/candidates/img121.jpg",
    canId: 12,
  },
  {
    id: 122,
    Adı: "Səid Abasov Əzizxan oğlu",
    Təvəllüd: "3/5/1980",
    DogYer: "Sabirabad",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaijan",
    img: "/candidates/img122.jpg",
    canId: 1,
  },
  {
    id: 123,
    Adı: "Elnur Quluzadə Qeyur oğlu",
    Təvəllüd: "11/10/1977",
    DogYer: "Bakı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaijan, Bakı",
    img: "/candidates/img123.jpg",
    canId: 134,
  },
  {
    id: 124,
    Adı: "Şükür Məmmədli Malik oğlu",
    Təvəllüd: "10/18/1954",
    DogYer: "İsmayıllı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaijan, İsmayıllı",
    img: "/candidates/img124.jpg",
    canId: 97,
  },
  {
    id: 125,
    Adı: "Şakir Məmmədov Sadıq oğlu",
    Təvəllüd: "7/5/1955",
    DogYer: "Goy-göl",
    Təhsil: "Orta-texniki",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya, S-Pg",
    img: "/candidates/img125.jpg",
    canId: 101,
  },
  {
    id: 126,
    Adı: "Əli Həsənov Hüseyn oğlu",
    Təvəllüd: "2/22/1972",
    DogYer: "Naxçıvan",
    Təhsil: "Orta",
    İxtisas: "Tibbi",
    Fəaliyyət: "Feldşer",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya, Smolensk",
    img: "/candidates/img126.jpg",
    canId: 67,
  },
  {
    id: 127,
    Adı: "Valeh İbrahimli Behbudalı oğlu",
    Təvəllüd: "5/28/1963",
    DogYer: "Qubadlı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "Musavat",
    Ölkəsi: "Azerbaycan, Qubadlı",
    img: "/candidates/img127.jpg",
    canId: 78,
  },
  {
    id: 128,
    Adı: "Şahin Şirinli Salam oğlu",
    Təvəllüd: "8/30/1953",
    DogYer: "İsnmayıllı",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Belçika",
    img: "/candidates/img128.jpg",
    canId: 153,
  },
  {
    id: 129,
    Adı: "Bəhruz Həşimov Feruz oğlu",
    Təvəllüd: "3/12/1985",
    DogYer: "Agdaş",
    Təhsil: "Orta",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Agdaş",
    img: "/candidates/img129.jpg",
    canId: 70,
  },
  {
    id: 130,
    Adı: "Əliyəddin Saadov Saad oğlu",
    Təvəllüd: "7/24/1969",
    DogYer: "Agdaş",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Agdaş",
    img: "/candidates/img130.jpg",
    canId: 142,
  },
  {
    id: 131,
    Adı: "Şahin Abdullayev Əjdər oğlu",
    Təvəllüd: "",
    DogYer: "Bakı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img131.jpg",
    canId: 6,
  },
  {
    id: 132,
    Adı: "Mətin Uluxanlı Hüseyn oğlu",
    Təvəllüd: "4/4/1973",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Hollandiya",
    img: "/candidates/img132.jpg",
    canId: 160,
  },
  {
    id: 133,
    Adı: "Rəhim Muradov İsa oğlu",
    Təvəllüd: "10/20/1975",
    DogYer: "Yardımlı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Yardımlı",
    img: "/candidates/img133.jpg",
    canId: 111,
  },
  {
    id: 134,
    Adı: "Anar Adıgözəlov Firayıl oğlu",
    Təvəllüd: "11/3/1976",
    DogYer: "Mingəçevir",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Mingəçevir",
    img: "/candidates/img134.jpg",
    canId: 10,
  },
  {
    id: 135,
    Adı: "Ruslan İsgəndərov Telman oğlu",
    Təvəllüd: "10/22/1985",
    DogYer: "",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya",
    img: "/candidates/img135.jpg",
    canId: 80,
  },
  {
    id: 136,
    Adı: "Razil Hüseynov Fazil oğlu",
    Təvəllüd: "8/10/1981",
    DogYer: "Gəncə",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Gəncə",
    img: "/candidates/img136.jpg",
    canId: 76,
  },
  {
    id: 137,
    Adı: "Şəmil Süleymanov Hüseyn oğlu",
    Təvəllüd: "7/10/1961",
    DogYer: "Laçın",
    Təhsil: "Ali",
    İxtisas: "Baytar",
    Fəaliyyət: "",
    Vətəndaşlıq: "Belarus",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Belarus",
    img: "/candidates/img137.jpg",
    canId: 157,
  },
  {
    id: 138,
    Adı: "Əvəz Zeynallı Tapdıq oğlu",
    Təvəllüd: "1/1/1970",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img138.jpg",
    canId: 174,
  },
  {
    id: 139,
    Adı: "Mirzə Manafov Tavar oğlu",
    Təvəllüd: "2/21/1968",
    DogYer: "Yardımlı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img139.jpg",
    canId: 91,
  },
  {
    id: 140,
    Adı: "Seyhun Feyziyev Dadaşbala oğılu",
    Təvəllüd: "11/25/1976",
    DogYer: "Bakı",
    Təhsil: "Orta",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Almaniya",
    img: "/candidates/img140.jpg",
    canId: 61,
  },
  {
    id: 141,
    Adı: "Famil Xəlilov Malik oğlu",
    Təvəllüd: "7/14/1990",
    DogYer: "Bakı",
    Təhsil: "",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img141.jpg",
    canId: 169,
  },
  {
    id: 142,
    Adı: "Elvin İsayev İltiham oğlu",
    Təvəllüd: "10/21/1980",
    DogYer: "Masallı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya, S-Pb",
    img: "/candidates/img142.jpg",
    canId: 79,
  },
  {
    id: 143,
    Adı: "Xuraman Qafarova Əşrəf qızı",
    Təvəllüd: "7/6/1958",
    DogYer: "Göyçay",
    Təhsil: "Ali",
    İxtisas: "Filoloq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img143.jpg",
    canId: 124,
  },
  {
    id: 144,
    Adı: "Ərəstun Oruclu Məmməd oğlu",
    Təvəllüd: "8/18/1963",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "ABŞ",
    img: "/candidates/img144.jpg",
    canId: 119,
  },
  {
    id: 145,
    Adı: "Şirvan Aydınov Rüstəm oğlu",
    Təvəllüd: "5/17/1970",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Ukraina",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Ukraina",
    img: "/candidates/img145.jpg",
    canId: 15,
  },
  {
    id: 146,
    Adı: "Elxan Abbasov Qardaşxan oğlu",
    Təvəllüd: "9/30/1960",
    DogYer: "Yevlax",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Estoniya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Estoniya",
    img: "/candidates/img146.jpg",
    canId: 2,
  },
  {
    id: 147,
    Adı: "Könül Əhmədova Vaqif qızı",
    Təvəllüd: "2/15/1977",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "",
    Vətəndaşlıq: "Estoniya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img147.jpg",
    canId: 41,
  },
  {
    id: 148,
    Adı: "Qurban Budaqlı İlqar oğlu",
    Təvəllüd: "6/27/2001",
    DogYer: "Beylaqan",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Beylagan",
    img: "/candidates/img148.jpg",
    canId: 23,
  },
  {
    id: 149,
    Adı: "Səxavət Cabbarov Ağaşirin oğlu",
    Təvəllüd: "6/15/1978",
    DogYer: "Agdaş",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Agdaş",
    img: "/candidates/img149.jpg",
    canId: 25,
  },
  {
    id: 150,
    Adı: "Emil Camalov Musa oğlu",
    Təvəllüd: "10/31/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "YAP",
    Ölkəsi: "ABŞ",
    img: "/candidates/img150.jpg",
    canId: 26,
  },
  {
    id: 151,
    Adı: "Yaşar Cəfərov Tahir oğlu",
    Təvəllüd: "10/31/1981",
    DogYer: "Goranboy",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Russiya, Moskva",
    img: "/candidates/img151.jpg",
    canId: 32,
  },
  {
    id: 152,
    Adı: "Arifə Cəfərova Arif qızı",
    Təvəllüd: "11/2/1975",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İnşatçı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img152.jpg",
    canId: 33,
  },
  {
    id: 153,
    Adı: "İdris Əhmədov Faxrəddin oğlu",
    Təvəllüd: "4/23/1986",
    DogYer: "Beylaqan",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Beylaqan",
    img: "/candidates/img153.jpg",
    canId: 38,
  },
  {
    id: 154,
    Adı: "Elman Əliyev Yaqub oğlu",
    Təvəllüd: "7/1/1963",
    DogYer: "Bakı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Fransa",
    img: "/candidates/img154.jpg",
    canId: 47,
  },
  {
    id: 155,
    Adı: "Namiq Əliyev Soltan oğlu",
    Təvəllüd: "3/10/1957",
    DogYer: "Kürdəmir",
    Təhsil: "Ali",
    İxtisas: "İqtisadcı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Russiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Russiya",
    img: "/candidates/img155.jpg",
    canId: 49,
  },
  {
    id: 156,
    Adı: "Ruslan Əliyev Rasim oğlu",
    Təvəllüd: "11/12/2001",
    DogYer: "Russiya",
    Təhsil: "Ali",
    İxtisas: "Aviasiya",
    Fəaliyyət: "",
    Vətəndaşlıq: "Russiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Fransa",
    img: "/candidates/img156.jpg",
    canId: 50,
  },
  {
    id: 157,
    Adı: "Rəfail Emçiyev Nizami oğlu",
    Təvəllüd: "3/8/1987",
    DogYer: "Balakən",
    Təhsil: "Orta",
    İxtisas: "Hərbi",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img157.jpg",
    canId: 52,
  },
  {
    id: 158,
    Adı: "Elmira Extibarova Nüsrət qızı",
    Təvəllüd: "3/8/1987",
    DogYer: "Rusiya",
    Təhsil: "Orta",
    İxtisas: "Tibb",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img158.jpg",
    canId: 55,
  },
  {
    id: 159,
    Adı: "Etibar Hacıyev Polad oğlu",
    Təvəllüd: "1/25/1967",
    DogYer: "Yevlax",
    Təhsil: "Orta",
    İxtisas: "Sürücü",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya",
    img: "/candidates/img159.jpg",
    canId: 63,
  },
  {
    id: 160,
    Adı: "Nurlan Hacıyev Elman oğlu",
    Təvəllüd: "10/25/1988",
    DogYer: "Quba",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya, Volqaqrad",
    img: "/candidates/img160.jpg",
    canId: 64,
  },
  {
    id: 161,
    Adı: "Nəsirəddin Kərəmov Yunus oğlu",
    Təvəllüd: "2/25/1950",
    DogYer: "Saatlı",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Saatlı",
    img: "/candidates/img161.jpg",
    canId: 85,
  },
  {
    id: 162,
    Adı: "Şakir Məmmədov Məhəmmədəli oğlu",
    Təvəllüd: "4/1/1960",
    DogYer: "Agstafa",
    Təhsil: "Ali",
    İxtisas: "Juranlist",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Sumqait",
    img: "/candidates/img162.jpg",
    canId: 101,
  },
  {
    id: 163,
    Adı: "Leyla Məmmədova Abbasqulu qızı",
    Təvəllüd: "2/19/1971",
    DogYer: "Naxçvan",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img163.jpg",
    canId: 105,
  },
  {
    id: 164,
    Adı: "Dilarə Miriyeva Qəzənfər qızı",
    Təvəllüd: "7/1/1959",
    DogYer: "Tovus",
    Təhsil: "Ali",
    İxtisas: "Juranlist",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img164.jpg",
    canId: 106,
  },
  {
    id: 165,
    Adı: "Firuzə Namazova Şahin qızı",
    Təvəllüd: "7/21/1995",
    DogYer: "Qəbələ",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Beylaqan",
    img: "/candidates/img165.jpg",
    canId: 115,
  },
  {
    id: 166,
    Adı: "Fərhad Orucov Bayram oğlu",
    Təvəllüd: "9/15/1967",
    DogYer: "Gədəbəy",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Rusiya",
    img: "/candidates/img166.jpg",
    canId: 120,
  },
  {
    id: 167,
    Adı: "Məcid Qasımov Kamal oğlu",
    Təvəllüd: "1/31/1987",
    DogYer: "Qazax",
    Təhsil: "Orta",
    İxtisas: "Hərbi",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan,Şəmkir",
    img: "/candidates/img167.jpg",
    canId: 126,
  },
  {
    id: 168,
    Adı: "Tamam Qasımzadə Rüstəm qızı",
    Təvəllüd: "8/12/1998",
    DogYer: "Bakı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img168.jpg",
    canId: 127,
  },
  {
    id: 169,
    Adı: "Kamil Rəşidov Cabbar oğlu",
    Təvəllüd: "7/15/1944",
    DogYer: "Qəbələ",
    Təhsil: "Ali",
    İxtisas: "Kimyaçı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img169.jpg",
    canId: 139,
  },
  {
    id: 170,
    Adı: "Validə Sarracova  Ələkbər qızı",
    Təvəllüd: "1/28/1966",
    DogYer: "Daşkəsən",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya",
    img: "/candidates/img170.jpg",
    canId: 148,
  },
  {
    id: 171,
    Adı: "Əli Şirvani Alməmməd oğlu",
    Təvəllüd: "12/14/1965",
    DogYer: "Cəlilabad",
    Təhsil: "Ali",
    İxtisas: "Sahibkar",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya, Uxta",
    img: "/candidates/img171.jpg",
    canId: 155,
  },
  {
    id: 172,
    Adı: "Haqverdi Tapdıqov Hüseyn oğlu",
    Təvəllüd: "8/5/1952",
    DogYer: "Kürdəmir",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AxƏd",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img172.jpg",
    canId: 158,
  },
  {
    id: 173,
    Adı: "Rəbiyyə Xanlarova Əli qızı",
    Təvəllüd: "6/6/1960",
    DogYer: "Bakı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Avstriya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Avstriya",
    img: "/candidates/img173.jpg",
    canId: 166,
  },
  {
    id: 174,
    Adı: "Xələfov Məhəmməd Molla oğlu",
    Təvəllüd: "7/1/1958",
    DogYer: "Ucar",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Avstriya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AxƏd",
    Ölkəsi: "Azərbaycan, Ucar",
    img: "/candidates/img174.jpg",
    canId: 168,
  },
  {
    id: 176,
    Adı: "Məzahir Məmmədov Məhərrəm oğlu",
    Təvəllüd: "x/x/1963",
    DogYer: "Ermənistan",
    Təhsil: "",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img176.jpg",
    canId: 176,
  },
];
