export const candidates = [
  {
    id: 1,
    Adı: "Abid Qafarov Abdin oğlu",
    Təvəllüd: "7/12/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
  },
  {
    id: 2,
    Adı: "Aygün Ələsgərova Sabir qızı",
    Təvəllüd: "1/20/1972",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Müəllimə",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, S-Pq",
  },
  {
    id: 3,
    Adı: "Cavanşir Xanlarov Məmməd oğlu",
    Təvəllüd: "3/1/1967",
    DogYer: "Bərdə",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Almaniya",
  },
  {
    id: 4,
    Adı: "Eldar Həmidov Soltanhəmid oğlu",
    Təvəllüd: "4/3/1958",
    DogYer: "Ucar",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "İnşaat",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Musavat",
    Ölkəsi: "Almaniya",
  },
  {
    id: 5,
    Adı: "Əli Kərimov Bəxtiyar oğlu",
    Təvəllüd: "6/1/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 6,
    Adı: "Əli Quliyev Əhməd oğlu",
    Təvəllüd: "5/20/1962",
    DogYer: "Qubadlı",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Vətəndaşlıq: "Ukrayna",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Ukrayna",
  },
  {
    id: 7,
    Adı: "Əlövsət Sadıqlı Əhəd oğlu",
    Təvəllüd: "2/3/1953",
    DogYer: "Ağdam",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 8,
    Adı: "Ənvər Ağamalızadə Yusif oğlu",
    Təvəllüd: "4/2/1953",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "Şair",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 9,
    Adı: "Faiq Kazımov Oruc oğlu",
    Təvəllüd: "12/29/1960",
    DogYer: "Şəmkir",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AĞ-Partiya",
    Ölkəsi: "Rusiya",
  },
  {
    id: 10,
    Adı: "Frizman Bağırov Cavad oğlu",
    Təvəllüd: "12/21/1983",
    DogYer: "Göy-göl",
    Təhsil: "Ali",
    İxtisas: "Psixoloq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Gürcüstan, Tiflis",
  },
  {
    id: 11,
    Adı: "Fuad Mahmudov Əbülfət oğlu",
    Təvəllüd: "7/26/1976",
    DogYer: "Mingəçevir",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Sahibkar",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    Ölkəsi: "Rusiya",
  },
  {
    id: 12,
    Adı: "Həsrət Telliyev Zeynal oğlu",
    Təvəllüd: "4/18/1960",
    DogYer: "Bəlakən",
    Təhsil: "Orta ",
    İxtisas: "İncəsənət",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bəlakən",
  },
  {
    id: 13,
    Adı: "İlqar Budaqov Namaz oğlu",
    Təvəllüd: "3/25/1969",
    DogYer: "Beyləqan",
    Təhsil: "Orta",
    İxtisas: "İşsiz",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Beyləqan",
  },
  {
    id: 14,
    Adı: "İlqar Hüseynli Bəxtiyar oğlu",
    Təvəllüd: "2/4/1990",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İqtisadiyyat",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya ",
  },
  {
    id: 15,
    Adı: "İqbal Məmmədli İman oğlu",
    Təvəllüd: "11/10/1959",
    DogYer: "Lənkəran",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Lənkəran",
  },
  {
    id: 16,
    Adı: "İsa Sadıqov Nəzər oğlu",
    Təvəllüd: "6/24/1958",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Hərbçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Norveç",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Norveç",
  },
  {
    id: 17,
    Adı: "Kəmalə Məmmədova Seydi qızı",
    Təvəllüd: "3/22/1977",
    DogYer: "Şəki",
    Təhsil: "Orta",
    İxtisas: "Tibb bacısı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Rusiya, Krasnoyarsk",
  },
  {
    id: 18,
    Adı: "Mübariz İsmayılov İsaq oğlu",
    Təvəllüd: "4/3/1966",
    DogYer: "Zaqatala",
    Təhsil: "Ali",
    İxtisas: "Zoomühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Zaqatala",
  },
  {
    id: 19,
    Adı: "Müşviq Əhmədli Seymur oğlu",
    Təvəllüd: "11/12/1990",
    DogYer: "Bərdə",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bərdə",
  },
  {
    id: 20,
    Adı: "Natiq Məmmədov Aydın oğlu",
    Təvəllüd: "3/20/1974",
    DogYer: "Naxçıvan",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 21,
    Adı: "Nurəddin Bayramov Məcid oğlu",
    Təvəllüd: "11/30/1958",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Naxçıvan",
  },
  {
    id: 22,
    Adı: "Oqtay İskəndərli İskəndər oğlu",
    Təvəllüd: "2/3/1959",
    DogYer: "Göyçay",
    Təhsil: "Ali",
    İxtisas: "iqtisadçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Fransa",
  },
  {
    id: 23,
    Adı: "Qurban Məmmədov Cəlal oğlu",
    Təvəllüd: "4/2/1959",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İngiltərə",
  },
  {
    id: 24,
    Adı: "Ramiz Orucov Məcid oğlu",
    Təvəllüd: "5/1/1952",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Fizik",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Gəncə",
  },
  {
    id: 25,
    Adı: "Razim Kərimov Əyyub oğlu",
    Təvəllüd: "9/24/1972",
    DogYer: "Neftçala",
    Təhsil: "Orta",
    İxtisas: "Ev ustası",
    Fəaliyyət: "Ev ustası",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 26,
    Adı: "Rəhim Mirzəyev Mirzəağa oğlu",
    Təvəllüd: "4/28/1970",
    DogYer: "Masallı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Almaniya",
  },
  {
    id: 27,
    Adı: "Rəşad Dadaşov Rufiq oğlu",
    Təvəllüd: "3/29/1983",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 28,
    Adı: "Rövşən Qəmbər Yunis oğlu",
    Təvəllüd: "6/3/1951",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
  },
  {
    id: 29,
    Adı: "Rza Səfərsoy Əli oğlu",
    Təvəllüd: "5/6/1976",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Hərbi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 30,
    Adı: "Sadiq Xankişiyev Nahdəli oğlu",
    Təvəllüd: "12/7/1963",
    DogYer: "Sabirabad",
    Təhsil: "Ali",
    Fəaliyyət: "Biznes",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Rusiya",
  },
  {
    id: 31,
    Adı: "Sahib Məmməd Camal oğlu",
    Təvəllüd: "12/20/1958",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Ədəbiyyat",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Gədəbəy",
  },
  {
    id: 32,
    Adı: "Sədaqət Paşayeva Saday qızı",
    Təvəllüd: "2/1/1972",
    DogYer: "Ağdam",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Türkiyə",
  },
  {
    id: 33,
    Adı: "Sərvan Kərimov İdris oğlu",
    Təvəllüd: "6/20/1958",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 34,
    Adı: "Sevil Muradova Mehbalı qızı",
    Təvəllüd: "1/5/1958",
    DogYer: "Bakı",
    Təhsil: "Orta",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 35,
    Adı: "Süleyman Məmmədhüseynov Qoca oğlu ",
    Təvəllüd: "4/23/1967",
    DogYer: "Ağdaş",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Ağdaş",
  },
  {
    id: 36,
    Adı: "Telman Ələkbərsoy Zaman oğlu",
    Təvəllüd: "10/25/1945",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbayan, Gədəbəy",
  },
  {
    id: 37,
    Adı: "Telman Verdiyev Salman oğlu",
    Təvəllüd: "5/29/1956",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İsveç",
  },
  {
    id: 38,
    Adı: "Təranə Səfərsoy Həsən qızı",
    Təvəllüd: "7/1/1970",
    DogYer: "Cəbrayıl",
    Təhsil: "Ali",
    İxtisas: "Əmtəəşünas",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 39,
    Adı: "Teymur Eminbəyli Nəbi oğlu",
    Təvəllüd: "3/3/1960",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İsveç",
  },
  {
    id: 40,
    Adı: "Tofiq Nüsrətov Yəhya oğlu",
    Təvəllüd: "5/13/1954",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, Moskva",
  },
  {
    id: 41,
    Adı: "Ülvi Namazlı Arif oğlu",
    Təvəllüd: "9/25/1974",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan,Qazax",
  },
  {
    id: 42,
    Adı: "Valeh Əliyev Hümmət oğlu",
    Təvəllüd: "9/13/1954",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Müsavat",
    Ölkəsi: "Azərbaycan, Salyan",
  },
  {
    id: 43,
    Adı: "Vaqif Əhmədov Qasım oğlu",
    Təvəllüd: "1/4/1959",
    DogYer: "Tovuz",
    Təhsil: "Ali",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Tovuz",
  },
  {
    id: 44,
    Adı: "Vüsal Ələkbərov Tofiq oğlu",
    Təvəllüd: "11/10/1972",
    DogYer: "Gəncə",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Gəncə",
  },
  {
    id: 45,
    Adı: "Xankişi Həsənov Nəcəf oğlu",
    Təvəllüd: "2/29/1964",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "Təhsil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
  },
  {
    id: 46,
    Adı: "Xatirə Cəbrayılova Sabir qızı",
    Təvəllüd: "12/23/1988",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Kimya",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, Moskva",
  },
  {
    id: 47,
    Adı: "Xatirə Rəhimli Əziz qızı",
    Təvəllüd: "5/25/1964",
    DogYer: "Ağsu",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 48,
    Adı: "Zakir Hüseyinov Səfxan oğlu",
    Təvəllüd: "2/3/1958",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Aqronom",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Fizuli",
  },
  {
    id: 49,
    Adı: "Zirəddin Abdullayev Sayad oğlu",
    Təvəllüd: "6/1/1947",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Filoloq",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Gəncə",
  },
  {
    id: 50,
    Adı: "Validə Əhmədova Gəncəli qızı",
    Təvəllüd: "5/22/1967",
    DogYer: "Laçın ",
    Təhsil: "Orta",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bərdə",
  },
  {
    id: 51,
    Adı: "Ruslan Fərzəliyev Sədrəddin oğlu",
    Təvəllüd: "6/11/1990",
    DogYer: "Sabirabad",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Şirvan",
  },
  {
    id: 52,
    Adı: "Səriyyə Qəmbərova Nurəddin qızı",
    Təvəllüd: "9/23/1985",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Naxçıvan",
  },
  {
    id: 53,
    Adı: "Vidadi Əhmədov Feyruz oğlu",
    Təvəllüd: "28/03/1956",
    DogYer: "Ucar",
    Təhsil: "Orta",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AzerFreedom",
    Ölkəsi: "Rusiya, N.Novqorod",
  },
  {
    id: 54,
    Adı: "Elxan Yusifov Oruc oğlu",
    Təvəllüd: "12/31/1950",
    DogYer: "Daşkəsən",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Daşkəsən",
  },
  {
    id: 55,
    Adı: "Tofiq Məmmədov Şirzad oğlu",
    Təvəllüd: "12/30/1978",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Y. Zelandiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "İnşaatçılar partiyası",
    Ölkəsi: "Y. Zelandiya",
  },
  {
    id: 56,
    Adı: "Fərid Salmanov İlqar oğlu",
    Təvəllüd: "5/7/1976",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya, Moskva",
  },
  {
    id: 57,
    Adı: "Anar Mirzəyev Nizam oğlu",
    Təvəllüd: "6/26/1978",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Lənkəran",
  },
  {
    id: 58,
    Adı: "Namizəd Səfərov Heydər oğlu",
    Təvəllüd: "1/10/1955",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 59,
    Adı: "Şahəddin Eyvazov Mayıl oğlu",
    Təvəllüd: "11/23/1960",
    DogYer: "Şəmkir",
    Təhsil: "Ali",
    İxtisas: "İncəsənət",
    Fəaliyyət: "Jurnalist",
    Vətəndaşlıq: "Fransa",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Fransa",
  },
  {
    id: 60,
    Adı: "Şahin İsmayılov Nurəddin oğlu",
    Təvəllüd: "6/9/1958",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İncəsənət",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Ukrayna",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "ASDP",
    Ölkəsi: "Ukrayna",
  },
  {
    id: 61,
    Adı: "Qələndər Aslanov Məhəmmədəli oğlu",
    Təvəllüd: "6/21/1963",
    DogYer: "Goranboy",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan, Goranboy",
  },
  {
    id: 62,
    Adı: "Əvəz Məmmədov Musa oğlu",
    Təvəllüd: "10/14/1970",
    DogYer: "Ordubad",
    Təhsil: "Ali",
    İxtisas: "İdman",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Ordubad",
  },
  {
    id: 63,
    Adı: "Didar Əhmədov Səbzulla oğlu",
    Təvəllüd: "6/2/1955",
    DogYer: "Qusar",
    Təhsil: "Ali",
    İxtisas: "İngilis",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Qusar",
  },
  {
    id: 64,
    Adı: "Ailə Eyvazova Musa qızı",
    Təvəllüd: "3/27/1955",
    DogYer: "Yevlax",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Yevlax",
  },
  {
    id: 65,
    Adı: "Qoşqar Movlayev Ənvər oğlu",
    Təvəllüd: "1/3/1980",
    DogYer: "Ermənistan, Ağbaba",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Ssenarist",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 66,
    Adı: "Aydın Ələkbərov İsaq oğlu",
    Təvəllüd: "7/29/1956",
    DogYer: "Yevlax",
    Təhsil: "Ali",
    İxtisas: "Tarix-psixologiya",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Müsavat",
    Ölkəsi: "Azərbaycan, Yevlax",
  },
  {
    id: 67,
    Adı: "Ataxan Əbilov Vəli oğlu",
    Təvəllüd: "6/29/1965",
    DogYer: "Azərbaycan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Hollandiya",
  },
  {
    id: 68,
    Adı: "Rüstəm Abdullayev Elman oğlu",
    Təvəllüd: "9/14/1988",
    DogYer: "Ağdam",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Ağdam",
  },
  {
    id: 69,
    Adı: "İsmayıl Abdullayev Mirbala oğlu ",
    Təvəllüd: "11/27/1973",
    DogYer: "Salyan",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Salyan",
  },
  {
    id: 70,
    Adı: "İlham Bayramov Eldar oğlu",
    Təvəllüd: "8/5/1967",
    DogYer: "Gürcüstan",
    Təhsil: "Orta",
    Fəaliyyət: "Fəhlə",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Zaqatala",
  },
  {
    id: 71,
    Adı: "Əfqan Ramazanov Aleksandr oğlu",
    Təvəllüd: "7/26/1979",
    DogYer: "Xaçmaz",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Xaçmaz",
  },
  {
    id: 72,
    Adı: "Ağaxan Abuşov Əlixas oğlu",
    Təvəllüd: "6/24/1965",
    DogYer: "Masallı",
    Təhsil: "Ali",
    İxtisas: "Din",
    Fəaliyyət: "İslam",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya",
  },
  {
    id: 73,
    Adı: "Sultani Rzayev Orucəliyeviç",
    Təvəllüd: "2/3/1964",
    DogYer: "Astara",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Biznes",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya",
  },
  {
    id: 74,
    Adı: "Ziyafət Abbasova Teymur qızı",
    Təvəllüd: "10/14/1972",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 75,
    Adı: "Məkisəd Mirzəyev Arif oğlu",
    Təvəllüd: "1/3/1967",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Aqranom",
    Fəaliyyət: "Siyasət",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "KXCP",
    Ölkəsi: "Azərbaycan, Qazax",
  },
  {
    id: 76,
    Adı: "Əli Bədəlov Mustafa oğlu",
    Təvəllüd: "3/20/1971",
    DogYer: "Salyan",
    Təhsil: "Orta",
    İxtisas: "İnşaatçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Salyan",
  },
  {
    id: 77,
    Adı: "Aslan Nəsibov Eldar oğlu",
    Təvəllüd: "12/31/1968",
    DogYer: "Gəncə",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Gəncə",
  },
  {
    id: 78,
    Adı: "Kamran Ağayev Kamil oğlu",
    Təvəllüd: "7/10/1987",
    DogYer: "Cəlilabad",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Cəlilabad",
  },
  {
    id: 79,
    Adı: "Fikrət Qəhrəmanov Əliqulu oğlu",
    Təvəllüd: "10/1/1969",
    DogYer: "Şabran",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Şabran",
  },
  {
    id: 80,
    Adı: "Cəmil Hacıyev Malik oğlu",
    Təvəllüd: "4/8/1977",
    DogYer: "Bakı",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 81,
    Adı: "Camal Bağırzadə Ramazan oğlu",
    Təvəllüd: "4/8/1957",
    DogYer: "Lənkaran",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 82,
    Adı: "Faiq Əliyev Məşədi oğlu",
    Təvəllüd: "3/14/1951",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Qazax",
  },
  {
    id: 83,
    Adı: "Şapur Qasimi Hüseyinqulu oğlu",
    Təvəllüd: "12/31/1946",
    DogYer: "Güney Azərbaycan",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 84,
    Adı: "Əzimbəy Hüseyinov Hümbət oğlu",
    Təvəllüd: "11/26/1967",
    DogYer: "Ermənistan",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 85,
    Adı: "Əhmədağa Nərimanov Hacıbala oğlu",
    Təvəllüd: "5/15/1953",
    DogYer: "Saatlı",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Saatlı",
  },
  {
    id: 86,
    Adı: "Vaqif Xankişiyev Tahir oğlu",
    Təvəllüd: "3/8/1978",
    DogYer: "Sabirabad",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Sabirabad",
  },
  {
    id: 87,
    Adı: "Elmar Bayramov Bəynişan oğlu",
    Təvəllüd: "3/28/1978",
    DogYer: "Daşkəsən",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Rusiya, Moskva",
  },
  {
    id: 88,
    Adı: "Ramiz Tağıyev Yusif oğlu",
    Təvəllüd: "6/8/1957",
    DogYer: "Bəlakən",
    Təhsil: "Ali",
    İxtisas: "Tarix",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan ",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
  },
  {
    id: 89,
    Adı: "Bilal Şirinov Mollaəli oğlu",
    Təvəllüd: "3/12/1956",
    DogYer: "Bəlakən",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan, Bəlakən",
  },
  {
    id: 90,
    Adı: "Fərid Qəribov Murad oğlu",
    Təvəllüd: "4/21/1986",
    DogYer: "Qəbələ",
    Təhsil: "Ali",
    İxtisas: "Hərbiçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Kanada",
  },
  {
    id: 91,
    Adı: "Qibləli Fərəcov Əli oğlu",
    Təvəllüd: "9/6/1959",
    DogYer: "Zərdab",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Zərdab",
  },
  {
    id: 92,
    Adı: "Əlisurət Cavadov Calal oğlu",
    Təvəllüd: "1/28/1955",
    DogYer: "Ağdaş",
    Təhsil: "Orta",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Ağdaş",
  },
  {
    id: 93,
    Adı: "Elşad Şükürov Nəriman oğlu",
    Təvəllüd: "9/1/1981",
    DogYer: "Cəbrayıl",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Cəbrayıl",
  },
  {
    id: 94,
    Adı: "Əkbər Cavadov Əsgər oğlu",
    Təvəllüd: "2/1/1958",
    DogYer: "Ağcabədi",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Ağcabədi",
  },
  {
    id: 95,
    Adı: "Mirqafur Seyidi Mirsədrəddin oğlu",
    Təvəllüd: "8/24/1955",
    DogYer: "Naftalan",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Naftalan",
  },
  {
    id: 96,
    Adı: "Babək Hüseynli Əsgərağa oğlu",
    Təvəllüd: "11/9/1981",
    DogYer: "Cəlilabad",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Cəlilabad",
  },
  {
    id: 97,
    Adı: "Həmid Həmidov Razim oğlu",
    Təvəllüd: "10/16/1988",
    DogYer: "Tovuz",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Tovuz",
  },
  {
    id: 98,
    Adı: "Ağası Məmmədli Baba oğlu",
    Təvəllüd: "4/8/1958",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Moldova",
  },
  {
    id: 99,
    Adı: "Yaşar Rəsulov Rəsul oğlu",
    Təvəllüd: "9/20/1963",
    DogYer: "Şəki",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Şəki",
  },
  {
    id: 100,
    Adı: "İlqar Quliyev May oğlu ",
    Təvəllüd: "1/1/1964",
    DogYer: "Kürdəmir",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Kürdəmir",
  },
  {
    id: 101,
    Adı: "Arzuman Xasməmmədli Yunis oğlu",
    Təvəllüd: "1/21/1957",
    DogYer: "Qazax",
    Təhsil: "Ali",
    Fəaliyyət: "Bələdiyə",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Qazax",
  },
  {
    id: 102,
    Adı: "Aslan Mehtiyev Nazim oğlu",
    Təvəllüd: "1/14/1985",
    DogYer: "Rustavi ",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Almaniya",
  },
  {
    id: 103,
    Adı: "Sahib Kərimli Fərman oğlu",
    Təvəllüd: "5/26/1974",
    DogYer: "Şəki",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Şəki",
  },
  {
    id: 104,
    Adı: "Hüseyn Mustafayev Sahib oğlu",
    Təvəllüd: "2/25/1990",
    DogYer: "Bərdə",
    Təhsil: "Orta",
    İxtisas: "Müsiqi",
    Fəaliyyət: "İncəsənət",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Bərdə",
  },
  {
    id: 105,
    Adı: "Fariz Şarifov Məhəmmədəli oğlu",
    Təvəllüd: "12/22/1957",
    DogYer: "Ağdaş",
    Təhsil: "Ali",
    İxtisas: "İdamançı",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Ağdaş",
  },
  {
    id: 106,
    Adı: "Oruc Yusifov İbrahim oölu",
    Təvəllüd: "1/22/1962",
    DogYer: "Ağstafa",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Vətəndaşlıq: "Ukrayna",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    Ölkəsi: "Ukrayna,Kiyev",
  },
  {
    id: 107,
    Adı: "Tural Sadıqlı Əlövsət oğlu",
    Təvəllüd: "6/10/1984",
    DogYer: "Ağdam",
    Təhsil: "Ali",
    İxtisas: "Şərqşünas",
    Fəaliyyət: "Siyasətşi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Almaniya",
  },
  {
    id: 108,
    Adı: "Ülviyyə Hüseynova Nağı qızı",
    Təvəllüd: "12/11/1977",
    DogYer: "Kürdəmir",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Türkiyə",
  },
  {
    id: 109,
    Adı: "Famil Bağırov Zaidağa oğlu",
    Təvəllüd: "2/15/1985",
    DogYer: "Astara",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan",
  },
  {
    id: 110,
    Adı: "Ravil Həsənov Adil oğlu",
    Təvəllüd: "8/16/1988",
    DogYer: "Xaçmaz",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan",
  },
  {
    id: 111,
    Adı: "İlham Zahirzadə Zaman oğlu",
    Təvəllüd: "1/27/1965",
    DogYer: "Şərur",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Ukrayna",
  },
  {
    id: 112,
    Adı: "Ənvər Rəhimov Cəlil oğlu",
    Təvəllüd: "12/24/1966",
    DogYer: "Culfa",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya,Smolensk",
  },
  {
    id: 113,
    Adı: "Elxan Cəfərov Əhməd oğlu",
    Təvəllüd: "1/8/1987",
    DogYer: "Ordubad",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, N. Çelnı",
  },
  {
    id: 114,
    Adı: "İlqar Əsgərov Eldar oğlu",
    Təvəllüd: 1964,
    DogYer: "Naxçıvan",
    Təhsil: "Orta",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Ukrayna, Vinnitsa",
  },
];
