export const navContents = [
  "News",
  "Regulations",
  "Elections",
  "About",
  "Contact Us",
  "State crimes",
  "Home",
];
export const urls = {
  info: "/news",
  "rules&regulations": "/documents",
  elections: "/elections",
  about: "/about",
  contactus: "/contact",
  tartar: "/tartar",
  home: "/",
};
export const totalLinks = [
  "/",
  "/news",
  "/news/announcements",
  "/news/decisions",
  "/news/newsLine",
  "/about",
  "about/aboutazxp",
  "about/counterteam",
  "about/deputies",
  "about/elccommision",
  "about/founders",
  "about/initiativegroup",
  "about/founders",
  "deputies",
  "deputies/deputies2024",
  "documents",
  "documents/archive",
  "documents/ebooks",
  "documents/regulations",
  "documents/statement",
  "elections",
  "elections/candidates",
  "elections/electioncommision",
  "elections/electionyear",
  "elections/candidates",
  "tartar",
  "tartar/ganzha",
  "tartar/nardaran",
  "tartar/ttorture",
];

export const mediaObject = [
  {
    id: 1,
    tv: "aba",
    produser: "Teymur Eminbəyli",
    since: "Since 2022",
    info: "",
    profile: "/candidates/img039.jpg",
    url: "https://www.youtube.com/channel/UCSL9utPCeQPbfP2sooaaUBg",
  },

  {
    id: 2,
    tv: "ayvaz",
    produser: "Şahəddin Ayvazoğlu",
    since: "Since 2023",
    info: "",
    profile: "/candidates/img059.jpg",
    url: "https://www.youtube.com/channel/UCFnIUjPKfLhS-wJO9pQkzdA",
  },
  {
    id: 3,
    tv: "freedom",
    produser: "Qurban Məmmədli",
    since: "Since 2018",
    info: "",
    profile: "/candidates/img023.jpg",
    url: "https://www.youtube.com/@AzerFreedomTV",
  },
  {
    id: 4,
    tv: "voice",
    produser: "Elxan Nuriyev",
    since: "Since 2024",
    info: "",
    profile: "/media/voiceofu.jpg",
    url: "https://www.youtube.com/@voiceofu91",
  },
  {
    id: 5,
    tv: "xural",
    produser: "Əvəz Zeynallı",
    since: "Since 2018",
    info: "",
    profile: "/candidates/img138.jpg",
    url: "https://www.youtube.com/c/XuralTV",
  },
  {
    id: 6,
    tv: "mgtv",
    produser: "Mustafa Gürbüz",
    since: "Since 2012",
    info: "",
    profile: "/media/mgtv.jpg",
    url: "https://www.youtube.com/channel/UCaBjlLrRL68E1o95J2IMNTw",
  },
  {
    id: 7,
    tv: "fotoinfo",
    produser: "Tarlan Novruzov",
    since: "Since 2019",
    info: "",
    profile: "/media/fotoinfo.jpg",
    url: "https://foto.info.az/gundem/22018-dasksnd-yerli-sahibkarlarla-gorus-kecirilib.html",
  },
];

export const tvprodusers = ["man"];

export const contacts = [
  { id: 1, media: "ABA TV", phones: [32333233, 32333233], email: "some email" },

  {
    id: 2,
    media: "AzerFreedom TV",
    phones: [32333233, 32333233],
    email: "some email",
  },
  {
    id: 3,
    media: "Xural TV",
    phones: [32333233, 32333233],
    email: "some email",
  },
  {
    id: 4,
    media: "Voice of You TV",
    phones: [32333233, 32333233],
    email: "some email",
  },
  {
    id: 5,
    media: "Eyvas Oglı TV",
    phones: [32333233, 32333233],
    email: "some email",
  },
  {
    id: 6,
    media: "Foto Info",
    phones: [32333233, 32333233],
    email: "some email",
  },
];
