export const cpdeputies2024 = [
  {
    idn: 1,
    name: "Qafarov Abid Abdin oğlu",
    dob: "7/12/1981",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "Mühəndis",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Almaniya",
    img: "/candidates/img001.jpg",
    canId: 123,
    vote: 8121,
  },
  {
    idn: 2,
    name: "Ələsgərova Aygün Sabir qızı",
    dob: "1/20/1972",
    birthPlace: "Lənkəran",
    education: "Ali",
    accupation: "Pedaqoq",
    profession: "Müəllimə",
    citizenship: "Rusiya",
    azcitizenship: "Bəli",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Rusiya, S-Pq",
    img: "/candidates/img002.jpg",
    canId: 46,
    vote: 4659,
  },
  {
    idn: 3,
    name: "Xanlarov Cavanşir Məmməd oğlu",
    dob: "3/1/1967",
    birthPlace: "Bərdə",
    education: "Ali",
    accupation: "Hüquq",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Almaniya",
    img: "/candidates/img003.jpg",
    canId: 165,
    vote: 2952,
  },
  {
    idn: 4,
    name: "Həmidov Eldar Soltanhəmid oğlu",
    dob: "4/3/1958",
    birthPlace: "Ucar",
    education: "Ali",
    accupation: "Mühəndis",
    profession: "İnşaat",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Musavat",
    country: "Almaniya",
    img: "/candidates/img004.jpg",
    canId: 65,
    vote: 2389,
  },
  {
    idn: 5,
    name: "Kərimov Əli Bəxtiyar oğlu",
    dob: "6/1/1981",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "Hüquq",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img005.jpg",
    canId: 87,
    vote: 3760,
  },
  {
    idn: 6,
    name: "Quliyev Əli Əhməd oğlu",
    dob: "5/20/1962",
    birthPlace: "Qubadlı",
    education: "Ali",
    accupation: "Həkim",
    citizenship: "Ukraina",
    azcitizenship: "Bəli",
    country: "Ukrayna",
    img: "/candidates/img006.jpg",
    canId: 132,
    vote: 5388,
  },
  {
    idn: 7,
    name: "Sadıqlı Əlövsət Əhəd oğlu",
    dob: "2/3/1953",
    birthPlace: "Ağdam",
    education: "Ali",
    accupation: "Pedaqoq",
    profession: "Hüquq",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "ADR",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img007.jpg",
    canId: 143,
    vote: 5929,
  },
  {
    idn: 8,
    name: "Ağamalızadə Ənvər Yusif oğlu",
    dob: "4/2/1953",
    birthPlace: "Ermənistan",
    education: "Ali",
    accupation: "Riyaziyyat",
    profession: "Şair",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "ADR",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img008.jpg",
    canId: 11,
    vote: 4846,
  },
  {
    idn: 10,
    name: "Bağırov Frizman Cavad oğlu",
    dob: "12/21/1983",
    birthPlace: "Göy-göl",
    education: "Ali",
    accupation: "Psixoloq",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Gürcüstan, Tiflis",
    img: "/candidates/img010.jpg",
    canId: 17,
    vote: 2800,
  },
  {
    idn: 14,
    name: "Hüseynli İlqar Bəxtiyar oğlu",
    dob: "2/4/1990",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "İqtisadiyyat",
    profession: "Media",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Rusiya ",
    img: "/candidates/img014.jpg",
    canId: 75,
    vote: 4885,
  },
  {
    idn: 16,
    name: "Sadıqov İsa Nəzər oğlu",
    dob: "6/24/1958",
    birthPlace: "Gürcüstan",
    education: "Ali",
    accupation: "Hərbçi",
    profession: "Siyasətçi",
    citizenship: "Norveç",
    azcitizenship: "Var",
    familystatus: "Evli",
    country: "Norveç",
    img: "/candidates/img016.jpg",
    canId: 145,
    vote: 5962,
  },
  {
    idn: 17,
    name: "Məmmədova Kəmalə Seydi qızı",
    dob: "3/22/1977",
    birthPlace: "Şəki",
    education: "Orta",
    accupation: "Tibb bacısı",
    citizenship: "Rusiya",
    azcitizenship: "Bəli",
    country: "Rusiya, Krasnoyarsk",
    img: "/candidates/img017.jpg",
    canId: 104,
    vote: 2969,
  },
  {
    idn: 19,
    name: "Əhmədli Müşviq Seymur oğlu",
    dob: "11/12/1990",
    birthPlace: "Bərdə",
    education: "Orta",
    accupation: "Hərbiçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Azərbaycan, Bərdə",
    img: "/candidates/img019.jpg",
    canId: 36,
    vote: 5883,
  },
  {
    idn: 21,
    name: "Bayramov Nurəddin Məcid oğlu",
    dob: "11/30/1958",
    birthPlace: "Naxçıvan",
    education: "Ali",
    accupation: "Tarixçi",
    profession: "Müəllim",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "ADR",
    country: "Azərbaycan, Naxçıvan",
    img: "/candidates/img021.jpg",
    canId: 21,
    vote: 3427,
  },
  {
    idn: 22,
    name: "İskəndərli Oqtay İskəndər oğlu",
    dob: "2/3/1959",
    birthPlace: "Göyçay",
    education: "Ali",
    accupation: "iqtisadçı",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Fransa",
    img: "/candidates/img022.jpg",
    canId: 81,
    vote: 5858,
  },
  {
    idn: 23,
    name: "Məmmədov Qurban Cəlal oğlu",
    dob: "4/2/1959",
    birthPlace: "Naxçıvan",
    education: "Ali",
    accupation: "Hüquqçu",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "İngiltərə",
    img: "/candidates/img023.jpg",
    canId: 100,
    vote: 7668,
  },
  {
    idn: 26,
    name: "Mirzəyev Rəhim Mirzəağa oğlu",
    dob: "4/28/1970",
    birthPlace: "Masallı",
    education: "Ali",
    accupation: "Hüquq",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Almaniya",
    img: "/candidates/img026.jpg",
    canId: 109,
    vote: 2593,
  },
  {
    idn: 27,
    name: "Dadaşov Rəşad Rufiq oğlu",
    dob: "3/29/1983",
    birthPlace: "Salyan",
    education: "Ali",
    accupation: "Tarixçi",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img027.jpg",
    canId: 34,
    vote: 6069,
  },
  {
    idn: 28,
    name: "Qəmbər Rövşən Yunis oğlu",
    dob: "6/3/1951",
    birthPlace: "Füzuli",
    education: "Ali",
    accupation: "Tarixçi",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Almaniya",
    img: "/candidates/img028.jpg",
    canId: 129,
    vote: 2638,
  },
  {
    idn: 29,
    name: "Səfərsoy Rza Əli oğlu",
    dob: "5/6/1976",
    birthPlace: "Salyan",
    education: "Ali",
    accupation: "Hərbi",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img029.jpg",
    canId: 150,
    vote: 6347,
  },
  {
    idn: 32,
    name: "Paşayeva Sədaqət Saday qızı",
    dob: "2/1/1972",
    birthPlace: "Ağdam",
    education: "Ali",
    accupation: "Tarixçi",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Subay",
    partimember: "AMMH",
    country: "Türkiyə",
    img: "/candidates/img032.jpg",
    canId: 122,
    vote: 4694,
  },
  {
    idn: 33,
    name: "Kərimov Sərvan İdris oğlu",
    dob: "6/20/1958",
    birthPlace: "Füzuli",
    education: "Ali",
    accupation: "Mühəndis",
    profession: "Təqaüdçü",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Subay",
    partimember: "Yox",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img033.jpg",
    canId: 89,
    vote: 2406,
  },
  {
    idn: 34,
    name: "Muradova Sevil Mehbalı qızı",
    dob: "1/5/1958",
    birthPlace: "Bakı",
    education: "Orta",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "AMMH",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img034.jpg",
    canId: 112,
    vote: 2824,
  },
  {
    idn: 37,
    name: "Verdiyev Telman Salman oğlu",
    dob: "5/29/1956",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "Hüquq",
    profession: "Hüquq",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "İsveç",
    img: "/candidates/img037.jpg",
    canId: 162,
    vote: 2953,
  },
  {
    idn: 38,
    name: "Səfərsoy Təranə Həsən qızı",
    dob: "7/1/1970",
    birthPlace: "Cəbrayıl",
    education: "Ali",
    accupation: "Əmtəəşünas",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "ADR",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img038.jpg",
    canId: 151,
    vote: 5318,
  },
  {
    idn: 39,
    name: "Eminbəyli Teymur Nəbi oğlu",
    dob: "3/3/1960",
    birthPlace: "Gürcüstan",
    education: "Ali",
    accupation: "Mühəndis",
    profession: "Media",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "İsveç",
    img: "/candidates/img039.jpg",
    canId: 53,
    vote: 6029,
  },
  {
    idn: 42,
    name: "Əliyev Valeh Hümmət oğlu",
    dob: "9/13/1954",
    birthPlace: "Salyan",
    education: "Ali",
    accupation: "Mühəndis",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "Müsavat",
    country: "Azərbaycan, Salyan",
    img: "/candidates/img042.jpg",
    canId: 51,
    vote: 2761,
  },
  {
    idn: 43,
    name: "Əhmədov Vaqif Qasım oğlu",
    dob: "1/4/1959",
    birthPlace: "Tovuz",
    education: "Ali",
    profession: "Media",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Azərbaycan, Tovuz",
    img: "/candidates/img043.jpg",
    canId: 39,
    vote: 3240,
  },
  {
    idn: 45,
    name: "Həsənov Xankişi Nəcəf oğlu",
    dob: "2/29/1964",
    birthPlace: "Quba",
    education: "Ali",
    accupation: "Riyaziyyat",
    profession: "education",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Almaniya",
    img: "/candidates/img045.jpg",
    canId: 69,
    vote: 3530,
  },
  {
    idn: 46,
    name: "Cəbrayılova Xatirə Sabir qızı",
    dob: "12/23/1988",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "Kimya",
    citizenship: "Rusiya",
    azcitizenship: "Bəli",
    partimember: "Yox",
    country: "Rusiya, Moskva",
    img: "/candidates/img046.jpg",
    canId: 30,
    vote: 7917,
  },
  {
    idn: 47,
    name: "Rəhimli Xatirə Əziz qızı",
    dob: "5/25/1964",
    birthPlace: "Ağsu",
    education: "Ali",
    accupation: "Jurnalist",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "Yox",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img047.jpg",
    canId: 137,
    vote: 4049,
  },
  {
    idn: 49,
    name: "Abdullayev Zirəddin Sayad oğlu",
    dob: "6/1/1947",
    birthPlace: "Gədəbəy",
    education: "Ali",
    accupation: "Filoloq",
    profession: "Müəllim",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "AMMH",
    country: "Azərbaycan, Gəncə",
    img: "/candidates/img049.jpg",
    canId: 7,
    vote: 3933,
  },
  {
    idn: 50,
    name: "Əhmədova Validə Gəncalı qızı",
    dob: "5/22/1967",
    birthPlace: "Laçın ",
    education: "Orta",
    profession: "İşsiz",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Subay",
    partimember: "Yox",
    country: "Azərbaycan, Bərdə",
    img: "/candidates/img050.jpg",
    canId: 42,
    vote: 7679,
  },
  {
    idn: 51,
    name: "Fərzəliyev Ruslan Sadəddin oğlu",
    dob: "6/11/1990",
    birthPlace: "Sabirabad",
    education: "Orta",
    accupation: "Hərbiçi",
    profession: "İşsiz",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Azərbaycan, Şirvan",
    img: "/candidates/img051.jpg",
    canId: 60,
    vote: 5522,
  },
  {
    idn: 52,
    name: "Qəmbərova Səriyyə Nurəddin qızı",
    dob: "9/23/1985",
    birthPlace: "Naxçıvan",
    education: "Ali",
    accupation: "Pedaqoq",
    profession: "İşsiz",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yox",
    country: "Azərbaycan, Naxçıvan",
    img: "/candidates/img052.jpg",
    canId: 130,
    vote: 4553,
  },
  {
    idn: 53,
    name: "Əhmədov Vidadi Feyruz oğlu",
    dob: "28/03/1956",
    birthPlace: "Ucar",
    education: "Orta",
    profession: "İş adamı",
    citizenship: "Rusiya",
    azcitizenship: "Bəli",
    partimember: "AzerFreedom",
    country: "Rusiya, N.Novqorod",
    img: "/candidates/img053.jpg",
    canId: 40,
    vote: 2387,
  },
  {
    idn: 55,
    name: "Məmmədov Tofiq Şirzad oğlu",
    dob: "12/30/1978",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "Hüquqçu",
    profession: "Siyasətçi",
    citizenship: "Y. Zelandiya",
    azcitizenship: "Bəli",
    partimember: "İnşaatçılar partiyası",
    country: "Y. Zelandiya",
    img: "/candidates/img055.jpg",
    canId: 103,
    vote: 3637,
  },
  {
    idn: 56,
    name: "Salmanov Fərid İlqar oğlu",
    dob: "5/7/1976",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "Jurnalist",
    profession: "İş adamı",
    citizenship: "Rusiya",
    azcitizenship: "Bəli",
    partimember: "Yoxdur",
    country: "Rusiya, Moskva",
    img: "/candidates/img056.jpg",
    canId: 146,
    vote: 2841,
  },
  {
    idn: 57,
    name: "Mirzəyev Anar Nizam oğlu",
    dob: "6/26/1978",
    birthPlace: "Lənkəran",
    education: "Ali",
    accupation: "Hüquqçu",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "Yoxdur",
    country: "Azərbaycan, Lənkəran",
    img: "/candidates/img057.jpg",
    canId: 107,
    vote: 2390,
  },
  {
    idn: 58,
    name: "Səfərov Namizəd Heydər oğlu",
    dob: "1/10/1955",
    birthPlace: "Naxçıvan",
    education: "Ali",
    accupation: "Hüquqçu",
    profession: "Vəkil",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "AMMH",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img058.jpg",
    canId: 149,
    vote: 6783,
  },
  {
    idn: 59,
    name: "Eyvazov Şahəddin Mayıl oğlu",
    dob: "11/23/1960",
    birthPlace: "Şəmkir",
    education: "Ali",
    accupation: "İncəsənət",
    profession: "Jurnalist",
    citizenship: "Fransa",
    azcitizenship: "Bəli",
    partimember: "AMMH",
    country: "Fransa",
    img: "/candidates/img059.jpg",
    canId: 56,
    vote: 3588,
  },
  {
    idn: 61,
    name: "Aslanov Qələndər Məhəmmədəli oğlu",
    dob: "6/21/1963",
    birthPlace: "Goranboy",
    education: "Ali",
    accupation: "Mühəndis",
    profession: "İşsiz",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "AXCP",
    country: "Azərbaycan, Goranboy",
    img: "/candidates/img061.jpg",
    canId: 14,
    vote: 3328,
  },
  {
    idn: 63,
    name: "Əhmədov Didar Səbzulla oğlu",
    dob: "6/2/1955",
    birthPlace: "Qusar",
    education: "Ali",
    accupation: "İngilis",
    profession: "Müəllim",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "Yoxdur",
    country: "Azərbaycan, Qusar",
    img: "/candidates/img063.jpg",
    canId: 37,
    vote: 2409,
  },
  {
    idn: 64,
    name: "Eyvazova Ailə Musa qızı",
    dob: "3/27/1955",
    birthPlace: "Yevlax",
    education: "Ali",
    accupation: "Hüquqçu",
    profession: "İşsiz",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yoxdur",
    country: "Azərbaycan, Yevlax",
    img: "/candidates/img064.jpg",
    canId: 57,
    vote: 5574,
  },
  {
    idn: 66,
    name: "Ələkbərov Aydın İsaq oğlu",
    dob: "7/29/1956",
    birthPlace: "Yevlax",
    education: "Ali",
    accupation: "Tarix-psixologiya",
    profession: "Təqaüdçü",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Müsavat",
    country: "Azərbaycan, Yevlax",
    img: "/candidates/img066.jpg",
    canId: 43,
    vote: 3604,
  },
  {
    idn: 67,
    name: "Əbilov Ataxan Vəli oğlu",
    dob: "6/29/1965",
    birthPlace: "Azərbaycan",
    education: "Ali",
    accupation: "Hüquqçu",
    profession: "Vəkil",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yoxdur",
    country: "Hollandiya",
    img: "/candidates/img067.jpg",
    canId: 35,
    vote: 6260,
  },
  {
    idn: 72,
    name: "Abuşov Ağaxan Əlixas oğlu",
    dob: "6/24/1965",
    birthPlace: "Masallı",
    education: "Ali",
    accupation: "Din",
    profession: "İslam",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yoxdur",
    country: "Rusiya",
    img: "/candidates/img072.jpg",
    canId: 9,
    vote: 4247,
  },
  {
    idn: 74,
    name: "Abbasova Ziyafət Teymur qızı",
    dob: "10/14/1972",
    birthPlace: "Gürcüstan",
    education: "Ali",
    accupation: "Riyaziyyat",
    profession: "İşsiz",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Subay",
    partimember: "ADR",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img074.jpg",
    canId: 3,
    vote: 7013,
  },
  {
    idn: 76,
    name: "Bədəlov Əli Mustafa oğlu",
    dob: "3/20/1971",
    birthPlace: "Salyan",
    education: "Orta",
    accupation: "İnşaatçı",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Azərbaycan, Salyan",
    img: "/candidates/img076.jpg",
    canId: 22,
    vote: 3187,
  },
  {
    idn: 78,
    name: "Ağayev Kamran Kamil oğlu",
    dob: "7/10/1987",
    birthPlace: "Cəlilabad",
    education: "Orta",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Azərbaycan, Cəlilabad",
    img: "/candidates/img078.jpg",
    canId: 13,
    vote: 2249,
  },
  {
    idn: 80,
    name: "Hacıyev Cəmil Malik oğlu",
    dob: "4/8/1977",
    birthPlace: "Bakı",
    education: "Ali",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img080.jpg",
    canId: 62,
    vote: 2350,
  },
  {
    idn: 81,
    name: "Bağırzadə Camal Ramazan oğlu",
    dob: "4/8/1957",
    birthPlace: "Lənkaran",
    education: "Ali",
    accupation: "Hüquqçu",
    profession: "Vəkil",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img081.jpg",
    canId: 18,
    vote: 4382,
  },
  {
    idn: 82,
    name: "Əliyev Faiq Məşədi oğlu",
    dob: "3/14/1951",
    birthPlace: "Qazax",
    education: "Ali",
    accupation: "Mühəndis",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Azərbaycan, Qazax",
    img: "/candidates/img082.jpg",
    canId: 48,
    vote: 2745,
  },
  {
    idn: 87,
    name: "Bayramov Elmar Bəynişan oğlu",
    dob: "3/28/1978",
    birthPlace: "Daşkəsən",
    education: "Ali",
    accupation: "Hüquq",
    citizenship: "Rusiya",
    azcitizenship: "Bəli",
    country: "Rusiya, Moskva",
    img: "/candidates/img087.jpg",
    canId: 19,
    vote: 5077,
  },
  {
    idn: 90,
    name: "Qəribov Fərid Murad oğlu",
    dob: "4/21/1986",
    birthPlace: "Qəbələ",
    education: "Ali",
    accupation: "Hərbiçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Kanada",
    img: "/candidates/img090.jpg",
    canId: 131,
    vote: 5475,
  },
  {
    idn: 98,
    name: "Məmmədli Ağası Baba oğlu",
    dob: "4/8/1958",
    birthPlace: "Quba",
    education: "Ali",
    accupation: "Jurnalist",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "AMMH",
    country: "Moldova",
    img: "/candidates/img098.jpg",
    canId: 95,
    vote: 2301,
  },
  {
    idn: 101,
    name: "Xasməmmədli Arzuman Yunis oğlu",
    dob: "1/21/1957",
    birthPlace: "Qazax",
    education: "Ali",
    profession: "Bələdiyə",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "AMMH",
    country: "Azərbaycan, Qazax",
    img: "/candidates/img101.jpg",
    canId: 167,
    vote: 2224,
  },
  {
    idn: 102,
    name: "Mehtiyev Aslan Nazim oğlu",
    dob: "1/14/1985",
    birthPlace: "Rustavi ",
    education: "Ali",
    accupation: "Hüquq",
    profession: "Siyasətçi",
    citizenship: "Rusiya",
    azcitizenship: "Bəli",
    partimember: "AMMH",
    country: "Almaniya",
    img: "/candidates/img102.jpg",
    canId: 92,
    vote: 3250,
  },
  {
    idn: 103,
    name: "Kərimli Sahib Fərman oğlu",
    dob: "5/26/1974",
    birthPlace: "Şəki",
    education: "Ali",
    accupation: "İqtisadçı",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    country: "Azərbaycan, Şəki",
    img: "/candidates/img103.jpg",
    canId: 86,
    vote: 4169,
  },
  {
    idn: 105,
    name: "Şərifov Fariz Məhəmmədismail oğlu",
    dob: "12/22/1957",
    birthPlace: "Ağdaş",
    education: "Ali",
    accupation: "İdamançı",
    profession: "Təqaüdçü",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "Yoxdur",
    country: "Azərbaycan, Ağdaş",
    img: "/candidates/img105.jpg",
    canId: 147,
    vote: 2265,
  },
  {
    idn: 107,
    name: "Sadıqlı Tural Əlövsət oğlu",
    dob: "6/10/1984",
    birthPlace: "Ağdam",
    education: "Ali",
    accupation: "Şərqşünas",
    profession: "Siyasətşi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Subay",
    partimember: "Yoxdur",
    country: "Almaniya",
    img: "/candidates/img107.jpg",
    canId: 144,
    vote: 8155,
  },
  {
    idn: 117,
    name: "Rəfiyeva Röya Tahir qızı",
    dob: "7/3/1981",
    birthPlace: "Oguz",
    education: "Ali",
    accupation: "Pedaqoq",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "Yox",
    country: "Almaniya",
    img: "/candidates/img117.jpg",
    canId: 136,
    vote: 3677,
  },
  {
    idn: 118,
    name: "Xəlilova Nurlana Xəlil qızı",
    dob: "10/11/1978",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "İqtisadçı",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    partimember: "Yox",
    country: "Azərbaican, Bakı",
    img: "/candidates/img118.jpg",
    canId: 170,
    vote: 4011,
  },
  {
    idn: 119,
    name: "Həsrətli Nüsrət Həsrət oğlu",
    dob: "10/10/1954",
    birthPlace: "Agdaş",
    education: "Ali",
    accupation: "Həkim",
    profession: "Həkim",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "Evli",
    partimember: "AMMN",
    country: "Azərbaican, Agdaş",
    img: "/candidates/img119.jpg",
    canId: 71,
    vote: 2988,
  },
  {
    idn: 121,
    name: "Ağaməmmədov Marif Ayaz oğlu",
    dob: "9/15/1966",
    birthPlace: "Agsu",
    education: "Ali",
    accupation: "",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "AXCP",
    country: "Alamaniya",
    img: "/candidates/img121.jpg",
    canId: 12,
    vote: 4084,
  },
  {
    idn: 122,
    name: "Abasov Səid Əzizxan oğlu",
    dob: "3/5/1980",
    birthPlace: "Sabirabad",
    education: "Ali",
    accupation: "",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaijan",
    img: "/candidates/img122.jpg",
    canId: 1,
    vote: 3655,
  },
  {
    idn: 124,
    name: "Məmmədli Şükür Malik oğlu",
    dob: "10/18/1954",
    birthPlace: "İsmayıllı",
    education: "Ali",
    accupation: "Hüquq",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaijan, İsmayıllı",
    img: "/candidates/img124.jpg",
    canId: 97,
    vote: 2807,
  },
  {
    idn: 125,
    name: "Məmmədov Şakir Məhəmmədəli oğlu",
    dob: "7/5/1955",
    birthPlace: "Goy-göl",
    education: "Orta-texniki",
    accupation: "Hüquq",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaijan, Sumqaıt",
    img: "/candidates/img162.jpg",
    canId: 101,
    vote: 2513,
  },
  {
    idn: 128,
    name: "Şirinli Şahin Salam oğlu",
    dob: "8/30/1953",
    birthPlace: "İsnmayıllı",
    education: "Ali",
    accupation: "Həkim",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Belçika",
    img: "/candidates/img128.jpg",
    canId: 153,
    vote: 2566,
  },
  {
    idn: 135,
    name: "İsgəndərov Ruslan Telman oğlu",
    dob: "10/22/1985",
    birthPlace: "",
    education: "Ali",
    accupation: "",
    profession: "",
    citizenship: "Rusiya",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Rusiya",
    img: "/candidates/img135.jpg",
    canId: 80,
    vote: 4155,
  },
  {
    idn: 138,
    name: "Zeynallı Əvəz Tapdıq oğlu",
    dob: "1/1/1970",
    birthPlace: "Gəncə",
    education: "Ali",
    accupation: "Hüquq",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan",
    img: "/candidates/img138.jpg",
    canId: 174,
    vote: 7442,
  },
  {
    idn: 139,
    name: "Manafov Mirzə Tavar oğlu",
    dob: "2/21/1968",
    birthPlace: "Yardımlı",
    education: "Ali",
    accupation: "Hüquq",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan",
    img: "/candidates/img139.jpg",
    canId: 91,
    vote: 2581,
  },
  {
    idn: 141,
    name: "Xəlilov Famil Malik oğlu",
    dob: "7/14/1990",
    birthPlace: "Bakı",
    education: "",
    accupation: "",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "AXCP",
    country: "Azərbaycan",
    img: "/candidates/img141.jpg",
    canId: 169,
    vote: 3978,
  },
  {
    idn: 142,
    name: "İsayev Elvin İltiham oğlu",
    dob: "10/21/1980",
    birthPlace: "Masallı",
    education: "Orta",
    accupation: "",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Rusiya, S-Pb",
    img: "/candidates/img142.jpg",
    canId: 79,
    vote: 5140,
  },
  {
    idn: 143,
    name: "Qafarova Xuraman Əşrəf qızı",
    dob: "7/6/1958",
    birthPlace: "Göyçay",
    education: "Ali",
    accupation: "Filoloq",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img143.jpg",
    canId: 124,
    vote: 3172,
  },
  {
    idn: 144,
    name: "Oruclu Ərəstun Məmməd oğlu",
    dob: "8/18/1963",
    birthPlace: "Gəncə",
    education: "Ali",
    accupation: "Həkim",
    profession: "Siyasətçi",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "ABŞ",
    img: "/candidates/img144.jpg",
    canId: 119,
    vote: 6947,
  },
  {
    idn: 147,
    name: "Əhmədova Könül Vaqif qızı",
    dob: "2/15/1977",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "Jurnalist",
    profession: "",
    citizenship: "Estoniya",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan",
    img: "/candidates/img147.jpg",
    canId: 41,
    vote: 4751,
  },
  {
    idn: 149,
    name: "Cabbarov Səxavət Ağaşirin oğlu",
    dob: "6/15/1978",
    birthPlace: "Agdaş",
    education: "Ali",
    accupation: "",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan, Agdaş",
    img: "/candidates/img149.jpg",
    canId: 25,
    vote: 2759,
  },
  {
    idn: 152,
    name: "Cəfərova Arifə Arif qızı",
    dob: "11/2/1975",
    birthPlace: "Bakı",
    education: "Ali",
    accupation: "İnşatçı",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img152.jpg",
    canId: 33,
    vote: 4049,
  },
  {
    idn: 156,
    name: "Əliyev Ruslan Rasim oğlu",
    dob: "11/12/2001",
    birthPlace: "Russiya",
    education: "Ali",
    accupation: "Aviasiya",
    profession: "",
    citizenship: "Russiya",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Fransa",
    img: "/candidates/img156.jpg",
    canId: 50,
    vote: 4572,
  },
  {
    idn: 157,
    name: "Emçiyev Rəfail Nizami oğlu",
    dob: "3/8/1987",
    birthPlace: "Balakən",
    education: "Orta",
    accupation: "Hərbi",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan",
    img: "/candidates/img157.jpg",
    canId: 52,
    vote: 3717,
  },
  {
    idn: 164,
    name: "Miriyeva Dilarə Qəzənfər qızı",
    dob: "7/1/1959",
    birthPlace: "Tovus",
    education: "Ali",
    accupation: "Juranlist",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "AMMH",
    country: "Azərbaycan, Bakı",
    img: "/candidates/img164.jpg",
    canId: 106,
    vote: 3979,
  },
  {
    idn: 165,
    name: "Namazova Firuzə Şahin qızı",
    dob: "7/21/1995",
    birthPlace: "Qəbələ",
    education: "Orta",
    accupation: "",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan, Beylaqan",
    img: "/candidates/img165.jpg",
    canId: 115,
    vote: 2653,
  },
  {
    idn: 167,
    name: "Qasımov Məcid Kamal oğlu",
    dob: "1/31/1987",
    birthPlace: "Qazax",
    education: "Orta",
    accupation: "Hərbi",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Azərbaycan,Şəmkir",
    img: "/candidates/img167.jpg",
    canId: 126,
    vote: 3284,
  },
  {
    idn: 173,
    name: "Xanlarova Rəbiyyə Əli qızı",
    dob: "6/6/1960",
    birthPlace: "Bakı",
    education: "Orta",
    accupation: "",
    profession: "",
    citizenship: "Avstriya",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Avstriya",
    img: "/candidates/img173.jpg",
    canId: 166,
    vote: 2466,
  },
  {
    idn: 178,
    name: "Abdullayeva Sənubər Məhəmməd qızı",
    dob: "2/28/1951",
    birthPlace: "Ermənistan",
    education: "Ali",
    accupation: "İdman",
    profession: "",
    citizenship: "Azərbaycan",
    azcitizenship: "Var",
    familystatus: "",
    partimember: "",
    country: "Rusiya",
    img: "/candidates/img178.jpg",
    canId: 8,
    vote: 3205,
  },
];
