export const deputies2024 = [
  {
    idn: 1,
    Adı: "Qafarov Abid Abdin oğlu",
    Təvəllüd: "7/12/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img001.jpg",
    canId: 123,
    vote: 8121,
  },
  {
    idn: 2,
    Adı: "Ələsgərova Aygün Sabir qızı",
    Təvəllüd: "1/20/1972",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Müəllimə",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, S-Peterburq",
    img: "/candidates/img002.jpg",
    canId: 46,
    vote: 4659,
  },
  {
    idn: 3,
    Adı: "Xanlarov Cavanşir Məmməd oğlu",
    Təvəllüd: "3/1/1967",
    DogYer: "Bərdə",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Almaniya",
    img: "/candidates/img003.jpg",
    canId: 165,
    vote: 2952,
  },
  {
    idn: 4,
    Adı: "Həmidov Eldar Soltanhəmid oğlu",
    Təvəllüd: "4/3/1958",
    DogYer: "Ucar",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "İnşaat",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Musavat",
    Ölkəsi: "Almaniya",
    img: "/candidates/img004.jpg",
    canId: 65,
    vote: 2389,
  },
  {
    idn: 5,
    Adı: "Kərimov Əli Bəxtiyar oğlu",
    Təvəllüd: "6/1/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img005.jpg",
    canId: 87,
    vote: 3760,
  },
  {
    idn: 6,
    Adı: "Quliyev Əli Əhməd oğlu",
    Təvəllüd: "5/20/1962",
    DogYer: "Qubadlı",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Vətəndaşlıq: "Ukraina",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Ukrayna",
    img: "/candidates/img006.jpg",
    canId: 132,
    vote: 5388,
  },
  {
    idn: 8,
    Adı: "Ağamalızadə Ənvər Yusif oğlu",
    Təvəllüd: "4/2/1953",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "Şair",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img008.jpg",
    canId: 11,
    vote: 4846,
  },
  {
    idn: 14,
    Adı: "Hüseynli İlqar Bəxtiyar oğlu",
    Təvəllüd: "2/4/1990",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İqtisadiyyat",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img014.jpg",
    canId: 75,
    vote: 4885,
  },
  {
    idn: 16,
    Adı: "Sadıqov İsa Nəzər oğlu",
    Təvəllüd: "6/24/1958",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Hərbçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Norveç",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Norveç",
    img: "/candidates/img016.jpg",
    canId: 145,
    vote: 5962,
  },
  {
    idn: 17,
    Adı: "Məmmədova Kəmalə Seydi qızı",
    Təvəllüd: "3/22/1977",
    DogYer: "Şəki",
    Təhsil: "Orta",
    İxtisas: "Tibb bacısı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Rusiya, Krasnoyarsk",
    img: "/candidates/img017.jpg",
    canId: 104,
    vote: 2969,
  },
  {
    idn: 19,
    Adı: "Əhmədli Müşviq Seymur oğlu",
    Təvəllüd: "11/12/1990",
    DogYer: "Bərdə",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bərdə",
    img: "/candidates/img019.jpg",
    canId: 36,
    vote: 5883,
  },
  {
    idn: 21,
    Adı: "Bayramov Nurəddin Məcid oğlu",
    Təvəllüd: "11/30/1958",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Naxçıvan",
    img: "/candidates/img021.jpg",
    canId: 21,
    vote: 3427,
  },
  {
    idn: 22,
    Adı: "İskəndərli Oqtay İskəndər oğlu",
    Təvəllüd: "2/3/1959",
    DogYer: "Göyçay",
    Təhsil: "Ali",
    İxtisas: "iqtisadçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Fransa",
    img: "/candidates/img022.jpg",
    canId: 81,
    vote: 5858,
  },
  {
    idn: 23,
    Adı: "Məmmədov Qurban Cəlal oğlu",
    Təvəllüd: "4/2/1959",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İngiltərə",
    img: "/candidates/img023.jpg",
    canId: 100,
    vote: 7668,
  },
  {
    idn: 28,
    Adı: "Qəmbər Rövşən Yunis oğlu",
    Təvəllüd: "6/3/1951",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img028.jpg",
    canId: 129,
    vote: 2638,
  },
  {
    idn: 29,
    Adı: "Səfərsoy Rza Əli oğlu",
    Təvəllüd: "5/6/1976",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Hərbi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img029.jpg",
    canId: 150,
    vote: 6347,
  },
  {
    idn: 32,
    Adı: "Paşayeva Sədaqət Saday qızı",
    Təvəllüd: "2/1/1972",
    DogYer: "Ağdam",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Türkiyə",
    img: "/candidates/img032.jpg",
    canId: 122,
    vote: 4694,
  },
  {
    idn: 33,
    Adı: "Kərimov Sərvan İdris oğlu",
    Təvəllüd: "6/20/1958",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img033.jpg",
    canId: 89,
    vote: 2406,
  },
  {
    idn: 34,
    Adı: "Muradova Sevil Mehbalı qızı",
    Təvəllüd: "1/5/1958",
    DogYer: "Bakı",
    Təhsil: "Orta",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img034.jpg",
    canId: 112,
    vote: 2824,
  },
  {
    idn: 37,
    Adı: "Verdiyev Telman Salman oğlu",
    Təvəllüd: "5/29/1956",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İsveç",
    img: "/candidates/img037.jpg",
    canId: 162,
    vote: 2953,
  },
  {
    idn: 38,
    Adı: "Səfərsoy Təranə Həsən qızı",
    Təvəllüd: "7/1/1970",
    DogYer: "Cəbrayıl",
    Təhsil: "Ali",
    İxtisas: "Əmtəəşünas",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img038.jpg",
    canId: 151,
    vote: 5318,
  },
  {
    idn: 39,
    Adı: "Eminbəyli Teymur Nəbi oğlu",
    Təvəllüd: "3/3/1960",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İsveç",
    img: "/candidates/img039.jpg",
    canId: 53,
    vote: 6029,
  },
  {
    idn: 42,
    Adı: "Əliyev Valeh Hümmət oğlu",
    Təvəllüd: "9/13/1954",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Müsavat",
    Ölkəsi: "Azərbaycan, Salyan",
    img: "/candidates/img042.jpg",
    canId: 51,
    vote: 2761,
  },
  {
    idn: 43,
    Adı: "Əhmədov Vaqif Qasım oğlu",
    Təvəllüd: "1/4/1959",
    DogYer: "Tovuz",
    Təhsil: "Ali",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Tovuz",
    img: "/candidates/img043.jpg",
    canId: 39,
    vote: 3240,
  },
  {
    idn: 45,
    Adı: "Həsənov Xankişi Nəcəf oğlu",
    Təvəllüd: "2/29/1964",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "Təhsil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img045.jpg",
    canId: 69,
    vote: 3530,
  },
  {
    idn: 46,
    Adı: "Cəbrayılova Xatirə Sabir qızı",
    Təvəllüd: "12/23/1988",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Kimya",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, Moskva",
    img: "/candidates/img046.jpg",
    canId: 30,
    vote: 7917,
  },
  {
    idn: 49,
    Adı: "Abdullayev Zirəddin Sayad oğlu",
    Təvəllüd: "6/1/1947",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Filoloq",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Gəncə",
    img: "/candidates/img049.jpg",
    canId: 7,
    vote: 3933,
  },
  {
    idn: 50,
    Adı: "Əhmədova Validə Gəncalı qızı",
    Təvəllüd: "5/22/1967",
    DogYer: "Laçın ",
    Təhsil: "Orta",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bərdə",
    img: "/candidates/img050.jpg",
    canId: 42,
    vote: 7679,
  },
  {
    idn: 51,
    Adı: "Fərzəliyev Ruslan Sədrəddin oğlu",
    Təvəllüd: "6/11/1990",
    DogYer: "Sabirabad",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Şirvan",
    img: "/candidates/img051.jpg",
    canId: 60,
    vote: 5522,
  },
  {
    idn: 52,
    Adı: "Qəmbərova Səriyyə Nurəddin qızı",
    Təvəllüd: "9/23/1985",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Naxçıvan",
    img: "/candidates/img052.jpg",
    canId: 130,
    vote: 4553,
  },
  {
    idn: 53,
    Adı: "Əhmədov Vidadi Feyruz oğlu",
    Təvəllüd: "28/03/1956",
    DogYer: "Ucar",
    Təhsil: "Orta",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AzerFreedom",
    Ölkəsi: "Rusiya, N.Novqorod",
    img: "/candidates/img053.jpg",
    canId: 40,
    vote: 2387,
  },
  {
    idn: 55,
    Adı: "Məmmədov Tofiq Şirzad oğlu",
    Təvəllüd: "12/30/1978",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Y. Zelandiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "İnşaatçılar partiyası",
    Ölkəsi: "Y. Zelandiya",
    img: "/candidates/img055.jpg",
    canId: 103,
    vote: 3637,
  },
  {
    idn: 57,
    Adı: "Mirzəyev Anar Nizam oğlu",
    Təvəllüd: "6/26/1978",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Lənkəran",
    img: "/candidates/img057.jpg",
    canId: 107,
    vote: 2390,
  },
  {
    idn: 58,
    Adı: "Səfərov Namizəd Heydər oğlu",
    Təvəllüd: "1/10/1955",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img058.jpg",
    canId: 149,
    vote: 6783,
  },
  {
    idn: 61,
    Adı: "Aslanov Qələndər Məhəmmədəli oğlu",
    Təvəllüd: "6/21/1963",
    DogYer: "Goranboy",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan, Goranboy",
    img: "/candidates/img061.jpg",
    canId: 14,
    vote: 3328,
  },
  {
    idn: 63,
    Adı: "Əhmədov Didar Səbzulla oğlu",
    Təvəllüd: "6/2/1955",
    DogYer: "Qusar",
    Təhsil: "Ali",
    İxtisas: "İngilis",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Qusar",
    img: "/candidates/img063.jpg",
    canId: 37,
    vote: 2409,
  },
  {
    idn: 64,
    Adı: "Eyvazova Ailə Musa qızı",
    Təvəllüd: "3/27/1955",
    DogYer: "Yevlax",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Yevlax",
    img: "/candidates/img064.jpg",
    canId: 57,
    vote: 5574,
  },
  {
    idn: 66,
    Adı: "Ələkbərov Aydın İsaq oğlu",
    Təvəllüd: "7/29/1956",
    DogYer: "Yevlax",
    Təhsil: "Ali",
    İxtisas: "Tarix-psixologiya",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Müsavat",
    Ölkəsi: "Azərbaycan, Yevlax",
    img: "/candidates/img066.jpg",
    canId: 43,
    vote: 3604,
  },
  {
    idn: 67,
    Adı: "Əbilov Ataxan Vəli oğlu",
    Təvəllüd: "6/29/1965",
    DogYer: "Azərbaycan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Hollandiya",
    img: "/candidates/img067.jpg",
    canId: 35,
    vote: 6260,
  },
  {
    idn: 72,
    Adı: "Abuşov Ağaxan Əlixas oğlu",
    Təvəllüd: "6/24/1965",
    DogYer: "Masallı",
    Təhsil: "Ali",
    İxtisas: "Din",
    Fəaliyyət: "İslam",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya",
    img: "/candidates/img072.jpg",
    canId: 9,
    vote: 4247,
  },
  {
    idn: 74,
    Adı: "Abbasova Ziyafət Teymur qızı",
    Təvəllüd: "10/14/1972",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img074.jpg",
    canId: 3,
    vote: 7013,
  },
  {
    idn: 76,
    Adı: "Bədəlov Əli Mustafa oğlu",
    Təvəllüd: "3/20/1971",
    DogYer: "Salyan",
    Təhsil: "Orta",
    İxtisas: "İnşaatçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Salyan",
    img: "/candidates/img076.jpg",
    canId: 22,
    vote: 3187,
  },
  {
    idn: 78,
    Adı: "Ağayev Kamran Kamil oğlu",
    Təvəllüd: "10/7/1987",
    DogYer: "Cəlilabad",
    Təhsil: "Kollec",
    İxtisas: "Kompyuter üzrə operator",
    Fəaliyyət: "İçtimai fəal",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Cəlilabad",
    img: "/candidates/img078.jpg",
    canId: 13,
    vote: 2249,
  },
  {
    idn: 80,
    Adı: "Hacıyev Cəmil Malik oğlu",
    Təvəllüd: "4/8/1977",
    DogYer: "Bakı",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img080.jpg",
    canId: 62,
    vote: 2350,
  },
  {
    idn: 81,
    Adı: "Bağırzadə Camal Ramazan oğlu",
    Təvəllüd: "4/8/1957",
    DogYer: "Lənkaran",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img081.jpg",
    canId: 18,
    vote: 4382,
  },
  {
    idn: 82,
    Adı: "Əliyev Faiq Məşədi oğlu",
    Təvəllüd: "3/14/1951",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Qazax",
    img: "/candidates/img082.jpg",
    canId: 48,
    vote: 2745,
  },
  {
    idn: 90,
    Adı: "Qəribov Fərid Murad oğlu",
    Təvəllüd: "4/21/1986",
    DogYer: "Qəbələ",
    Təhsil: "Ali",
    İxtisas: "Hərbiçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Kanada",
    img: "/candidates/img090.jpg",
    canId: 131,
    vote: 5475,
  },
  {
    idn: 98,
    Adı: "Məmmədli Ağası Baba oğlu",
    Təvəllüd: "4/8/1958",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Moldova",
    img: "/candidates/img098.jpg",
    canId: 95,
    vote: 2301,
  },
  {
    idn: 101,
    Adı: "Xasməmmədli Arzuman Yunis oğlu",
    Təvəllüd: "1/21/1957",
    DogYer: "Qazax",
    Təhsil: "Ali",
    Fəaliyyət: "Bələdiyə",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Qazax",
    img: "/candidates/img101.jpg",
    canId: 167,
    vote: 2224,
  },
  {
    idn: 102,
    Adı: "Mehtiyev Aslan Nazim oğlu",
    Təvəllüd: "1/14/1985",
    DogYer: "Rustavi ",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Almaniya",
    img: "/candidates/img102.jpg",
    canId: 92,
    vote: 3250,
  },
  {
    idn: 103,
    Adı: "Kərimli Sahib Fərman oğlu",
    Təvəllüd: "5/26/1974",
    DogYer: "Şəki",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Şəki",
    img: "/candidates/img103.jpg",
    canId: 86,
    vote: 4169,
  },
  {
    idn: 105,
    Adı: "Şərifov Fariz Məhəmmədismayıl oğlu",
    Təvəllüd: "12/22/1957",
    DogYer: "Ağdaş",
    Təhsil: "Ali",
    İxtisas: "İdamançı",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Ağdaş",
    img: "/candidates/img105.jpg",
    canId: 147,
    vote: 2265,
  },
  {
    idn: 119,
    Adı: "Həsrətli Nüsrət Həsrət oğlu",
    Təvəllüd: "10/10/1954",
    DogYer: "Ağdaş",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "Həkim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AMMN",
    Ölkəsi: "Azərbaycan, Agdaş",
    img: "/candidates/img119.jpg",
    canId: 71,
    vote: 2988,
  },
  {
    idn: 122,
    Adı: "Abasov Səid Əzizxan oğlu",
    Təvəllüd: "3/5/1980",
    DogYer: "Sabirabad",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img122.jpg",
    canId: 1,
    vote: 3655,
  },
  {
    idn: 124,
    Adı: "Məmmədli Şükür Malik oğlu",
    Təvəllüd: "10/18/1954",
    DogYer: "İsmayıllı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, İsmayıllı",
    img: "/candidates/img124.jpg",
    canId: 97,
    vote: 2807,
  },
  {
    idn: 125,
    Adı: "Məmmədov Şakir Məhəmmədəli oğlu",
    Təvəllüd: "7/5/1955",
    DogYer: "Goy-göl",
    Təhsil: "Orta-texniki",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Sumqayıt",
    img: "/candidates/img162.jpg",
    canId: 101,
    vote: 2513,
  },
  {
    idn: 128,
    Adı: "Şirinli Şahin Salam oğlu",
    Təvəllüd: "8/30/1953",
    DogYer: "İsnmayıllı",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Belçika",
    img: "/candidates/img128.jpg",
    canId: 153,
    vote: 2566,
  },
  {
    idn: 138,
    Adı: "Zeynallı Əvəz Tapdıq oğlu",
    Təvəllüd: "1/1/1970",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img138.jpg",
    canId: 174,
    vote: 7442,
  },
  {
    idn: 139,
    Adı: "Manafov Mirzə Tavar oğlu",
    Təvəllüd: "2/21/1968",
    DogYer: "Yardımlı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img139.jpg",
    canId: 91,
    vote: 2581,
  },
  {
    idn: 141,
    Adı: "Xəlilov Famil Malik oğlu",
    Təvəllüd: "7/14/1990",
    DogYer: "Bakı",
    Təhsil: "",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img141.jpg",
    canId: 169,
    vote: 3978,
  },
  {
    idn: 142,
    Adı: "İsayev Elvin İltiham oğlu",
    Təvəllüd: "10/21/1980",
    DogYer: "Masallı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya, S-Peterburq",
    img: "/candidates/img142.jpg",
    canId: 79,
    vote: 5140,
  },
  {
    idn: 143,
    Adı: "Qafarova Xuraman Əşrəf qızı",
    Təvəllüd: "7/6/1958",
    DogYer: "Göyçay",
    Təhsil: "Ali",
    İxtisas: "Filoloq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img143.jpg",
    canId: 124,
    vote: 3172,
  },
  {
    idn: 144,
    Adı: "Oruclu Ərəstun Məmməd oğlu",
    Təvəllüd: "8/18/1963",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "ABŞ",
    img: "/candidates/img144.jpg",
    canId: 119,
    vote: 6947,
  },
  {
    idn: 149,
    Adı: "Cabbarov Səxavət Ağaşirin oğlu",
    Təvəllüd: "6/15/1978",
    DogYer: "Agdaş",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Agdaş",
    img: "/candidates/img149.jpg",
    canId: 25,
    vote: 2759,
  },
  {
    idn: 152,
    Adı: "Cəfərova Arifə Arif qızı",
    Təvəllüd: "11/2/1975",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İnşatçı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img152.jpg",
    canId: 33,
    vote: 4049,
  },
  {
    idn: 156,
    Adı: "Əliyev Ruslan Rasim oğlu",
    Təvəllüd: "11/12/2001",
    DogYer: "Russiya",
    Təhsil: "Ali",
    İxtisas: "Aviasiya",
    Fəaliyyət: "",
    Vətəndaşlıq: "Russiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Fransa",
    img: "/candidates/img156.jpg",
    canId: 50,
    vote: 4572,
  },
  {
    idn: 157,
    Adı: "Emçiyev Rəfail Nizami oğlu",
    Təvəllüd: "3/8/1987",
    DogYer: "Balakən",
    Təhsil: "Orta",
    İxtisas: "Hərbi",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img157.jpg",
    canId: 52,
    vote: 3717,
  },
  {
    idn: 164,
    Adı: "Miriyeva Dilarə Qəzənfər qızı",
    Təvəllüd: "7/1/1959",
    DogYer: "Tovus",
    Təhsil: "Ali",
    İxtisas: "Juranlist",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img164.jpg",
    canId: 106,
    vote: 3979,
  },
  {
    idn: 173,
    Adı: "Xanlarova Rəbiyyə Əli qızı",
    Təvəllüd: "6/6/1960",
    DogYer: "Bakı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Avstriya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Avstriya",
    img: "/candidates/img173.jpg",
    canId: 166,
    vote: 2466,
  },
  {
    idn: 178,
    Adı: "Abdullayeva Sənubər Məhəmməd qızı",
    Təvəllüd: "2/28/1951",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "İdman",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya",
    img: "/candidates/img178.jpg",
    canId: 8,
    vote: 3205,
  },
  {
    idn: 179,
    Adı: "Məmməd Sahib Camal oğlu",
    Təvəllüd: "12/25/1958",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Ədəbiyyat",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img179.jpg",
    canId: 94,
    vote: 2174,
  },
  {
    idn: 180,
    Adı: "Həmidov Həmid Razim oğlu",
    Təvəllüd: "10/16/1958",
    DogYer: "Tovus",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img180.jpg",
    canId: 66,
    vote: 2146,
  },
  {
    idn: 181,
    Adı: "Qasimi Şapur Hüseyinqulu oğlu",
    Təvəllüd: "12/31/1946",
    DogYer: "Güney Azərbaycan",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img180.jpg",
    canId: 66,
    vote: 2120,
  },
  {
    idn: 182,
    Adı: "Hüseynli Babək Əsgərağa oğlu",
    Təvəllüd: "11/19/1981",
    DogYer: "Cəlilabad",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img182.jpg",
    canId: 74,
    vote: 2095,
  },
  {
    idn: 183,
    Adı: "Cəfərov Yasar Tahir oğlu",
    Təvəllüd: "09/14/1970",
    DogYer: "Goranboy",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya",
    img: "/candidates/img183.jpg",
    canId: 74,
    vote: 2034,
  },
  {
    idn: 184,
    Adı: "Ələkbərsoy Telman Zaman oğlu",
    Təvəllüd: "10/25/1945",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img184.jpg",
    canId: 42,
    vote: 1995,
  },
  {
    idn: 185,
    Adı: "Ismayılov Mübariz Isaq oğlu",
    Təvəllüd: "04/03/1966",
    DogYer: "Zaqatala",
    Təhsil: "Ali",
    İxtisas: "Zoomühəndis",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img185.jpg",
    canId: 82,
    vote: 1939,
  },
  {
    idn: 187,
    Adı: "Camalov Emil Musa oğlu",
    Təvəllüd: "10/31/1981",
    DogYer: "Azərbaycan",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "YAP",
    Ölkəsi: "ABŞ",
    img: "/candidates/img187.jpg",
    canId: 26,
    vote: 1833,
  },
  {
    idn: 188,
    Adı: "Əliyev Namiq Soltan oğlu",
    Təvəllüd: "03/10/1957",
    DogYer: "Kürdəmir",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "YAP",
    Ölkəsi: "Rusiya",
    img: "/candidates/img188.jpg",
    canId: 49,
    vote: 1799,
  },
  {
    idn: 189,
    Adı: "Rəsulov Yasar Rəsul oğlu",
    Təvəllüd: "09/20/1963",
    DogYer: "Şəki",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img189.jpg",
    canId: 140,
    vote: 1868,
  },
  {
    idn: 190,
    Adı: "Mahmudov Fuad Əbülfət oğlu",
    Təvəllüd: "07/26/1976",
    DogYer: "Minqəçevir",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya",
    img: "/candidates/img190.jpg",
    canId: 90,
    vote: 1797,
  },
  {
    idn: 191,
    Adı: "Məmmğdhüseynov Süleyman Qoca oğlu",
    Təvəllüd: "07/26/1976",
    DogYer: "Agdaş",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img191.jpg",
    canId: 94,
    vote: 1787,
  },
  {
    idn: 192,
    Adı: "İsmayılov Şahin Nurəddin oğlu",
    Təvəllüd: "06/09/1958",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Ukrayna",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ASDP",
    Ölkəsi: "Ukrayna",
    img: "/candidates/img192.jpg",
    canId: 66,
    vote: 1767,
  },
  {
    idn: 193,
    Adı: "Hüseynov Zakir Səfxan oğlu",
    Təvəllüd: "02/03/1958",
    DogYer: "Fizuli",
    Təhsil: "Ali",
    İxtisas: "Aqronom",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img193.jpg",
    canId: 73,
    vote: 1760,
  },
  {
    idn: 194,
    Adı: "Zülfüqarova Sevinc Əflan qızı",
    Təvəllüd: "12/33/1979",
    DogYer: "Şamaxı",
    Təhsil: "Ali",
    İxtisas: "Prodüser",
    Fəaliyyət: "",
    Vətəndaşlıq: "Alamaniya",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AMMG",
    Ölkəsi: "Almaniya",
    img: "/candidates/img194.jpg",
    canId: 100,
    vote: 1446,
  },
  {
    idn: 196,
    Adı: "Saniyev Samir Fəxrəddin oğlu",
    Təvəllüd: "03/09/1971",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquqşunas",
    Fəaliyyət: "Hüquqçu",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img196.jpg",
    canId: 85,
    vote: 1270,
  },
  {
    idn: 197,
    Adı: "İsrafilov Mehdi Rəcəbəli oğlu",
    Təvəllüd: "08/01/1960",
    DogYer: "Massallı",
    Təhsil: "Orta",
    İxtisas: "Aqranom",
    Fəaliyyət: "Aqranom",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AzerFree",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img197.jpg",
    canId: 53,
    vote: 1270,
  },
  {
    idn: 198,
    Adı: "Atayev Murtuzəli Yusran oğlu",
    Təvəllüd: "07/10/1987",
    DogYer: "Caliabad",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AzerFree",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img198.jpg",
    canId: 9,
    vote: 1249,
  },
  {
    idn: 199,
    Adı: "Rüstəmov Rüstəm İsa oğlu",
    Təvəllüd: "01/15/1952",
    DogYer: "Gazax",
    Təhsil: "Ali",
    İxtisas: "Konstruktor",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya",
    img: "/candidates/img199.jpg",
    canId: 83,
    vote: 1105,
  },
  {
    idn: 200,
    Adı: "Aydınov Şirvan Rüstəm oğlu",
    Təvəllüd: "05/17/1970",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "Hüquqşünas",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Ukrayna",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AzerFree",
    Ölkəsi: "Hollandiya",
    img: "/candidates/img200.jpg",
    canId: 13,
    vote: 1096,
  },
  {
    idn: 201,
    Adı: "Məmmədov Əvəz Musa oğlu",
    Təvəllüd: "10/14/1970",
    DogYer: "Ordubad",
    Təhsil: "Ali",
    İxtisas: "İdman",
    Fəaliyyət: "İdman müəllimi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img201.jpg",
    canId: 64,
    vote: 1056,
  },
  {
    idn: 202,
    Adı: "Aga Qalib Şəmsəddin oğlu",
    Təvəllüd: "02/13/1961",
    DogYer: "Minqəçevir",
    Təhsil: "Ali",
    İxtisas: "Hüquqşunas",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img202.jpg",
    canId: 7,
    vote: 1056,
  },
  {
    idn: 203,
    Adı: "Nağdəliyev Məhəmməd Nagdəli oğlu",
    Təvəllüd: "07/23/1959",
    DogYer: "Naxçivan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Ukrayna",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AzerFree",
    Ölkəsi: "İsveçrə",
    img: "/candidates/img203.jpg",
    canId: 72,
    vote: 1040,
  },
  {
    idn: 204,
    Adı: "Sükürov Elşad Nəriman oğlu",
    Təvəllüd: "09/01/1981",
    DogYer: "Gəbrayıl",
    Təhsil: "Orta",
    İxtisas: "İş adamı",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AzerFree",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img204.jpg",
    canId: 93,
    vote: 1017,
  },
  {
    idn: 205,
    Adı: "Adigözəlov Anar Firayıl oğlu",
    Təvəllüd: "11/03/1976",
    DogYer: "Minqəçevir",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Elektronçu",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img205.jpg",
    canId: 6,
    vote: 1005,
  },
  {
    idn: 206,
    Adı: "Atayev Elxan Eniş oğlu",
    Təvəllüd: "04/28/1978",
    DogYer: "Tibilisi",
    Təhsil: "Ali",
    İxtisas: "Tərcüməçi",
    Fəaliyyət: "Tərcüməçi",
    Vətəndaşlıq: "Fransa",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Fransa",
    img: "/candidates/img206.jpg",
    canId: 11,
    vote: 971,
  },
  {
    idn: 207,
    Adı: "Kərəmov Nəsirəddin Yunus oğlu",
    Təvəllüd: "02/25/1950",
    DogYer: "Saatlı",
    Təhsil: "Ali",
    İxtisas: "Hüquqşunas",
    Fəaliyyət: "Hüquqçu",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AzƏd",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img207.jpg",
    canId: 54,
    vote: 934,
  },
  {
    idn: 208,
    Adı: "Seyidi Mirqafir Mirsədrəddin oğlu",
    Təvəllüd: "08/24/1955",
    DogYer: "Naftalan",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img208.jpg",
    canId: 152,
    vote: 1333,
  },
  {
    idn: 209,
    Adı: "Mirzəyev Məkisəd Arif oğlu",
    Təvəllüd: "01/03/1967",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Aqranom",
    Fəaliyyət: "Siyasət",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "KXCP",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img209.jpg",
    canId: 108,
    vote: 1334,
  },
  {
    idn: 210,
    Adı: "Şirinov Bilal Mollaəli oğlu",
    Təvəllüd: "03/12/1956",
    DogYer: "Balakən",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img210.jpg",
    canId: 108,
    vote: 1309,
  },
  {
    idn: 211,
    Adı: "Budaqov İlqar Namaz oğlu",
    Təvəllüd: "03/25/1956",
    DogYer: "Beylaqan",
    Təhsil: "Orta",
    İxtisas: "İşsiz",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img211.jpg",
    canId: 109,
    vote: 1279,
  },
  {
    idn: 212,
    Adı: "Əliyev Elnur Süleyman oğlu",
    Təvəllüd: "02/05/1978",
    DogYer: "Agdam",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "Sürücü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AzerFree",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img212.jpg",
    canId: 110,
    vote: 786,
  },
  {
    idn: 213,
    Adı: "Quliyeva Gültəkin Sərvan qızı",
    Təvəllüd: "10/10/1994",
    DogYer: "Agdam",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "Jurnalist",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img444.jpg",
    canId: 111,
    vote: 849,
  },
  {
    idn: 214,
    Adı: "Korkmaz (Məsimzadə) Tahirə Eyvaz qızı",
    Təvəllüd: "10/05/1951",
    DogYer: "Qəbələ",
    Təhsil: "Ali",
    İxtisas: "Rəssam",
    Fəaliyyət: "Rəssam",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Türkiyə, İzmir",
    img: "/candidates/img214.jpg",
    canId: 112,
    vote: 849,
  },
  {
    idn: 215,
    Adı: "Hacıyeva Şəhla Malik qızı",
    Təvəllüd: "02/04/1972",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İqtisasçı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "İsveç",
    img: "/candidates/img215.jpg",
    canId: 113,
    vote: 748,
  },
  {
    idn: 216,
    Adı: "Kərimli Pünhan Vahid oğlu",
    Təvəllüd: "07/07/1989",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Filoloq",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img216.jpg",
    canId: 114,
    vote: 695,
  },
  {
    idn: 217,
    Adı: "Məhərrəmov Vahid Tofiq oğlu",
    Təvəllüd: "08/03/1997",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İdman",
    Fəaliyyət: "İdmançı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img217.jpg",
    canId: 115,
    vote: 581,
  },
  {
    idn: 218,
    Adı: "Pursüleyman Hüseyin Abbas oğlu",
    Təvəllüd: "09/21/1987",
    DogYer: "Biləsuvar",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "İsvecrə",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "İsvecrə, Luzern",
    img: "/candidates/img218.jpg",
    canId: 116,
    vote: 543,
  },
  {
    idn: 219,
    Adı: "Ağayev Ağaismayıl Musa oğlu",
    Təvəllüd: "09/01/1965",
    DogYer: "Zərdab",
    Təhsil: "Ali",
    İxtisas: "Mühandis",
    Fəaliyyət: "Fərdi biznes",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Mingəçevir",
    img: "/candidates/img219.jpg",
    canId: 117,
    vote: 516,
  },
  {
    idn: 220,
    Adı: "Nəsirov Zakir Nəsir oğlu",
    Təvəllüd: "08/07/1959",
    DogYer: "Şirvan",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Əmtəəşünas",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "RF, S-Peterburq",
    img: "/candidates/img220.jpg",
    canId: 118,
    vote: 491,
  },
  {
    idn: 221,
    Adı: "Ağayev Mütəllim Musa oğlu",
    Təvəllüd: "07/16/1976",
    DogYer: "Zərdab",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "Fərdi biznes",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Zərdab",
    img: "/candidates/img221.jpg",
    canId: 119,
    vote: 476,
  },
  {
    idn: 222,
    Adı: "Axundov Mirzəağa Tofiq oğlu",
    Təvəllüd: "06/03/1966",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Fərdi biznes",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Lənkəran",
    img: "/candidates/img222.jpg",
    canId: 120,
    vote: 474,
  },
  {
    idn: 223,
    Adı: "Məhərrəmi Zakir Kamran oğlu",
    Təvəllüd: "04/05/1956",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Rabitəçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Gəncə",
    img: "/candidates/img223.jpg",
    canId: 121,
    vote: 460,
  },
  {
    idn: 224,
    Adı: "Bayramov Zubeyir Zakir oğlu",
    Təvəllüd: "01/16/1956",
    DogYer: "Ağdaş",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Mühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AMMG",
    Ölkəsi: "Azərbaycan, Agdaş",
    img: "/candidates/img224.jpg",
    canId: 122,
    vote: 452,
  },
];
