export const deputies2024 = [
  {
    idn: 1,
    Adı: "Qafarov Abid Abdin oğlu",
    Təvəllüd: "7/12/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img001.jpg",
    canId: 123,
    vote: 8121,
  },
  {
    idn: 2,
    Adı: "Ələsgərova Aygün Sabir qızı",
    Təvəllüd: "1/20/1972",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "Müəllimə",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, S-Pq",
    img: "/candidates/img002.jpg",
    canId: 46,
    vote: 4659,
  },
  {
    idn: 3,
    Adı: "Xanlarov Cavanşir Məmməd oğlu",
    Təvəllüd: "3/1/1967",
    DogYer: "Bərdə",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Almaniya",
    img: "/candidates/img003.jpg",
    canId: 165,
    vote: 2952,
  },
  {
    idn: 4,
    Adı: "Həmidov Eldar Soltanhəmid oğlu",
    Təvəllüd: "4/3/1958",
    DogYer: "Ucar",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "İnşaat",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Musavat",
    Ölkəsi: "Almaniya",
    img: "/candidates/img004.jpg",
    canId: 65,
    vote: 2389,
  },
  {
    idn: 5,
    Adı: "Kərimov Əli Bəxtiyar oğlu",
    Təvəllüd: "6/1/1981",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img005.jpg",
    canId: 87,
    vote: 3760,
  },
  {
    idn: 6,
    Adı: "Quliyev Əli Əhməd oğlu",
    Təvəllüd: "5/20/1962",
    DogYer: "Qubadlı",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Vətəndaşlıq: "Ukraina",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Ukrayna",
    img: "/candidates/img006.jpg",
    canId: 132,
    vote: 5388,
  },
  // {
  //   idn: 7,
  //   Adı: "Sadıqlı Əlövsət Əhəd oğlu",
  //   Təvəllüd: "2/3/1953",
  //   DogYer: "Ağdam",
  //   Təhsil: "Ali",
  //   İxtisas: "Pedaqoq",
  //   Fəaliyyət: "Hüquq",
  //   Vətəndaşlıq: "Azərbaycan",
  //   AzVətOlubmu: "Var",
  //   AiləStatus: "Evli",
  //   PartiaÜzvi: "ADR",
  //   Ölkəsi: "Azərbaycan, Bakı",
  //   img: "/candidates/img007.jpg",
  //   canId: 143,
  //   vote: 5929,
  // },
  {
    idn: 8,
    Adı: "Ağamalızadə Ənvər Yusif oğlu",
    Təvəllüd: "4/2/1953",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "Şair",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img008.jpg",
    canId: 11,
    vote: 4846,
  },
  // {
  //   idn: 10,
  //   Adı: "Bağırov Frizman Cavad oğlu",
  //   Təvəllüd: "12/21/1983",
  //   DogYer: "Göy-göl",
  //   Təhsil: "Ali",
  //   İxtisas: "Psixoloq",
  //   Vətəndaşlıq: "Azərbaycan",
  //   AzVətOlubmu: "Var",
  //   Ölkəsi: "Gürcüstan, Tiflis",
  //   img: "/candidates/img010.jpg",
  //   canId: 17,
  //   vote: 2800,
  // },
  {
    idn: 14,
    Adı: "Hüseynli İlqar Bəxtiyar oğlu",
    Təvəllüd: "2/4/1990",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İqtisadiyyat",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya ",
    img: "/candidates/img014.jpg",
    canId: 75,
    vote: 4885,
  },
  {
    idn: 16,
    Adı: "Sadıqov İsa Nəzər oğlu",
    Təvəllüd: "6/24/1958",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Hərbçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Norveç",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Norveç",
    img: "/candidates/img016.jpg",
    canId: 145,
    vote: 5962,
  },
  {
    idn: 17,
    Adı: "Məmmədova Kəmalə Seydi qızı",
    Təvəllüd: "3/22/1977",
    DogYer: "Şəki",
    Təhsil: "Orta",
    İxtisas: "Tibb bacısı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    Ölkəsi: "Rusiya, Krasnoyarsk",
    img: "/candidates/img017.jpg",
    canId: 104,
    vote: 2969,
  },
  {
    idn: 19,
    Adı: "Əhmədli Müşviq Seymur oğlu",
    Təvəllüd: "11/12/1990",
    DogYer: "Bərdə",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bərdə",
    img: "/candidates/img019.jpg",
    canId: 36,
    vote: 5883,
  },
  {
    idn: 21,
    Adı: "Bayramov Nurəddin Məcid oğlu",
    Təvəllüd: "11/30/1958",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Naxçıvan",
    img: "/candidates/img021.jpg",
    canId: 21,
    vote: 3427,
  },
  {
    idn: 22,
    Adı: "İskəndərli Oqtay İskəndər oğlu",
    Təvəllüd: "2/3/1959",
    DogYer: "Göyçay",
    Təhsil: "Ali",
    İxtisas: "iqtisadçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Fransa",
    img: "/candidates/img022.jpg",
    canId: 81,
    vote: 5858,
  },
  {
    idn: 23,
    Adı: "Məmmədov Qurban Cəlal oğlu",
    Təvəllüd: "4/2/1959",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İngiltərə",
    img: "/candidates/img023.jpg",
    canId: 100,
    vote: 7668,
  },
  {
    idn: 28,
    Adı: "Qəmbər Rövşən Yunis oğlu",
    Təvəllüd: "6/3/1951",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img028.jpg",
    canId: 129,
    vote: 2638,
  },
  {
    idn: 29,
    Adı: "Səfərsoy Rza Əli oğlu",
    Təvəllüd: "5/6/1976",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Hərbi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img029.jpg",
    canId: 150,
    vote: 6347,
  },
  {
    idn: 32,
    Adı: "Paşayeva Sədaqət Saday qızı",
    Təvəllüd: "2/1/1972",
    DogYer: "Ağdam",
    Təhsil: "Ali",
    İxtisas: "Tarixçi",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Türkiyə",
    img: "/candidates/img032.jpg",
    canId: 122,
    vote: 4694,
  },
  {
    idn: 33,
    Adı: "Kərimov Sərvan İdris oğlu",
    Təvəllüd: "6/20/1958",
    DogYer: "Füzuli",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img033.jpg",
    canId: 89,
    vote: 2406,
  },
  {
    idn: 34,
    Adı: "Muradova Sevil Mehbalı qızı",
    Təvəllüd: "1/5/1958",
    DogYer: "Bakı",
    Təhsil: "Orta",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img034.jpg",
    canId: 112,
    vote: 2824,
  },
  {
    idn: 37,
    Adı: "Verdiyev Telman Salman oğlu",
    Təvəllüd: "5/29/1956",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "Hüquq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İsveç",
    img: "/candidates/img037.jpg",
    canId: 162,
    vote: 2953,
  },
  {
    idn: 38,
    Adı: "Səfərsoy Təranə Həsən qızı",
    Təvəllüd: "7/1/1970",
    DogYer: "Cəbrayıl",
    Təhsil: "Ali",
    İxtisas: "Əmtəəşünas",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img038.jpg",
    canId: 151,
    vote: 5318,
  },
  {
    idn: 39,
    Adı: "Eminbəyli Teymur Nəbi oğlu",
    Təvəllüd: "3/3/1960",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "İsveç",
    img: "/candidates/img039.jpg",
    canId: 53,
    vote: 6029,
  },
  {
    idn: 42,
    Adı: "Əliyev Valeh Hümmət oğlu",
    Təvəllüd: "9/13/1954",
    DogYer: "Salyan",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Müsavat",
    Ölkəsi: "Azərbaycan, Salyan",
    img: "/candidates/img042.jpg",
    canId: 51,
    vote: 2761,
  },
  {
    idn: 43,
    Adı: "Əhmədov Vaqif Qasım oğlu",
    Təvəllüd: "1/4/1959",
    DogYer: "Tovuz",
    Təhsil: "Ali",
    Fəaliyyət: "Media",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Tovuz",
    img: "/candidates/img043.jpg",
    canId: 39,
    vote: 3240,
  },
  {
    idn: 45,
    Adı: "Həsənov Xankişi Nəcəf oğlu",
    Təvəllüd: "2/29/1964",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "Təhsil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img045.jpg",
    canId: 69,
    vote: 3530,
  },
  {
    idn: 46,
    Adı: "Cəbrayılova Xatirə Sabir qızı",
    Təvəllüd: "12/23/1988",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Kimya",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Rusiya, Moskva",
    img: "/candidates/img046.jpg",
    canId: 30,
    vote: 7917,
  },
  {
    idn: 47,
    Adı: "Rəhimli Xatirə Əziz qızı",
    Təvəllüd: "5/25/1964",
    DogYer: "Ağsu",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img047.jpg",
    canId: 137,
    vote: 4049,
  },
  {
    idn: 49,
    Adı: "Abdullayev Zirəddin Sayad oğlu",
    Təvəllüd: "6/1/1947",
    DogYer: "Gədəbəy",
    Təhsil: "Ali",
    İxtisas: "Filoloq",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Gəncə",
    img: "/candidates/img049.jpg",
    canId: 7,
    vote: 3933,
  },
  {
    idn: 50,
    Adı: "Əhmədova Validə Gəncalı qızı",
    Təvəllüd: "5/22/1967",
    DogYer: "Laçın ",
    Təhsil: "Orta",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Bərdə",
    img: "/candidates/img050.jpg",
    canId: 42,
    vote: 7679,
  },
  {
    idn: 51,
    Adı: "Fərzəliyev Ruslan Sadəddin oğlu",
    Təvəllüd: "6/11/1990",
    DogYer: "Sabirabad",
    Təhsil: "Orta",
    İxtisas: "Hərbiçi",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Şirvan",
    img: "/candidates/img051.jpg",
    canId: 60,
    vote: 5522,
  },
  {
    idn: 52,
    Adı: "Qəmbərova Səriyyə Nurəddin qızı",
    Təvəllüd: "9/23/1985",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Azərbaycan, Naxçıvan",
    img: "/candidates/img052.jpg",
    canId: 130,
    vote: 4553,
  },
  {
    idn: 53,
    Adı: "Əhmədov Vidadi Feyruz oğlu",
    Təvəllüd: "28/03/1956",
    DogYer: "Ucar",
    Təhsil: "Orta",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AzerFreedom",
    Ölkəsi: "Rusiya, N.Novqorod",
    img: "/candidates/img053.jpg",
    canId: 40,
    vote: 2387,
  },
  {
    idn: 55,
    Adı: "Məmmədov Tofiq Şirzad oğlu",
    Təvəllüd: "12/30/1978",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Y. Zelandiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "İnşaatçılar partiyası",
    Ölkəsi: "Y. Zelandiya",
    img: "/candidates/img055.jpg",
    canId: 103,
    vote: 3637,
  },
  {
    idn: 56,
    Adı: "Salmanov Fərid İlqar oğlu",
    Təvəllüd: "5/7/1976",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "İş adamı",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya, Moskva",
    img: "/candidates/img056.jpg",
    canId: 146,
    vote: 2841,
  },
  {
    idn: 57,
    Adı: "Mirzəyev Anar Nizam oğlu",
    Təvəllüd: "6/26/1978",
    DogYer: "Lənkəran",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Lənkəran",
    img: "/candidates/img057.jpg",
    canId: 107,
    vote: 2390,
  },
  {
    idn: 58,
    Adı: "Səfərov Namizəd Heydər oğlu",
    Təvəllüd: "1/10/1955",
    DogYer: "Naxçıvan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img058.jpg",
    canId: 149,
    vote: 6783,
  },
  {
    idn: 59,
    Adı: "Eyvazov Şahəddin Mayıl oğlu",
    Təvəllüd: "11/23/1960",
    DogYer: "Şəmkir",
    Təhsil: "Ali",
    İxtisas: "İncəsənət",
    Fəaliyyət: "Jurnalist",
    Vətəndaşlıq: "Fransa",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Fransa",
    img: "/candidates/img059.jpg",
    canId: 56,
    vote: 3588,
  },
  {
    idn: 61,
    Adı: "Aslanov Qələndər Məhəmmədəli oğlu",
    Təvəllüd: "6/21/1963",
    DogYer: "Goranboy",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan, Goranboy",
    img: "/candidates/img061.jpg",
    canId: 14,
    vote: 3328,
  },
  {
    idn: 63,
    Adı: "Əhmədov Didar Səbzulla oğlu",
    Təvəllüd: "6/2/1955",
    DogYer: "Qusar",
    Təhsil: "Ali",
    İxtisas: "İngilis",
    Fəaliyyət: "Müəllim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Qusar",
    img: "/candidates/img063.jpg",
    canId: 37,
    vote: 2409,
  },
  {
    idn: 64,
    Adı: "Eyvazova Ailə Musa qızı",
    Təvəllüd: "3/27/1955",
    DogYer: "Yevlax",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Yevlax",
    img: "/candidates/img064.jpg",
    canId: 57,
    vote: 5574,
  },
  {
    idn: 66,
    Adı: "Ələkbərov Aydın İsaq oğlu",
    Təvəllüd: "7/29/1956",
    DogYer: "Yevlax",
    Təhsil: "Ali",
    İxtisas: "Tarix-psixologiya",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Müsavat",
    Ölkəsi: "Azərbaycan, Yevlax",
    img: "/candidates/img066.jpg",
    canId: 43,
    vote: 3604,
  },
  {
    idn: 67,
    Adı: "Əbilov Ataxan Vəli oğlu",
    Təvəllüd: "6/29/1965",
    DogYer: "Azərbaycan",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Hollandiya",
    img: "/candidates/img067.jpg",
    canId: 35,
    vote: 6260,
  },
  {
    idn: 72,
    Adı: "Abuşov Ağaxan Əlixas oğlu",
    Təvəllüd: "6/24/1965",
    DogYer: "Masallı",
    Təhsil: "Ali",
    İxtisas: "Din",
    Fəaliyyət: "İslam",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Rusiya",
    img: "/candidates/img072.jpg",
    canId: 9,
    vote: 4247,
  },
  {
    idn: 74,
    Adı: "Abbasova Ziyafət Teymur qızı",
    Təvəllüd: "10/14/1972",
    DogYer: "Gürcüstan",
    Təhsil: "Ali",
    İxtisas: "Riyaziyyat",
    Fəaliyyət: "İşsiz",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Subay",
    PartiaÜzvi: "ADR",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img074.jpg",
    canId: 3,
    vote: 7013,
  },
  {
    idn: 76,
    Adı: "Bədəlov Əli Mustafa oğlu",
    Təvəllüd: "3/20/1971",
    DogYer: "Salyan",
    Təhsil: "Orta",
    İxtisas: "İnşaatçı",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Salyan",
    img: "/candidates/img076.jpg",
    canId: 22,
    vote: 3187,
  },
  {
    idn: 78,
    Adı: "Ağayev Kamran Kamil oğlu",
    Təvəllüd: "10/7/1987",
    DogYer: "Cəlilabad",
    Təhsil: "Kollec",
    İxtisas: "Kompyuter üzrə operator",
    Fəaliyyət: "İçtimai fəal",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    Ölkəsi: "Azərbaycan, Cəlilabad",
    img: "/candidates/img078.jpg",
    canId: 13,
    vote: 2249,
  },
  {
    idn: 80,
    Adı: "Hacıyev Cəmil Malik oğlu",
    Təvəllüd: "4/8/1977",
    DogYer: "Bakı",
    Təhsil: "Ali",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img080.jpg",
    canId: 62,
    vote: 2350,
  },
  {
    idn: 81,
    Adı: "Bağırzadə Camal Ramazan oğlu",
    Təvəllüd: "4/8/1957",
    DogYer: "Lənkaran",
    Təhsil: "Ali",
    İxtisas: "Hüquqçu",
    Fəaliyyət: "Vəkil",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img081.jpg",
    canId: 18,
    vote: 4382,
  },
  {
    idn: 82,
    Adı: "Əliyev Faiq Məşədi oğlu",
    Təvəllüd: "3/14/1951",
    DogYer: "Qazax",
    Təhsil: "Ali",
    İxtisas: "Mühəndis",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Qazax",
    img: "/candidates/img082.jpg",
    canId: 48,
    vote: 2745,
  },
  {
    idn: 90,
    Adı: "Qəribov Fərid Murad oğlu",
    Təvəllüd: "4/21/1986",
    DogYer: "Qəbələ",
    Təhsil: "Ali",
    İxtisas: "Hərbiçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Kanada",
    img: "/candidates/img090.jpg",
    canId: 131,
    vote: 5475,
  },
  {
    idn: 98,
    Adı: "Məmmədli Ağası Baba oğlu",
    Təvəllüd: "4/8/1958",
    DogYer: "Quba",
    Təhsil: "Ali",
    İxtisas: "Jurnalist",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Moldova",
    img: "/candidates/img098.jpg",
    canId: 95,
    vote: 2301,
  },
  {
    idn: 101,
    Adı: "Xasməmmədli Arzuman Yunis oğlu",
    Təvəllüd: "1/21/1957",
    DogYer: "Qazax",
    Təhsil: "Ali",
    Fəaliyyət: "Bələdiyə",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Qazax",
    img: "/candidates/img101.jpg",
    canId: 167,
    vote: 2224,
  },
  {
    idn: 102,
    Adı: "Mehtiyev Aslan Nazim oğlu",
    Təvəllüd: "1/14/1985",
    DogYer: "Rustavi ",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Bəli",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Almaniya",
    img: "/candidates/img102.jpg",
    canId: 92,
    vote: 3250,
  },
  {
    idn: 103,
    Adı: "Kərimli Sahib Fərman oğlu",
    Təvəllüd: "5/26/1974",
    DogYer: "Şəki",
    Təhsil: "Ali",
    İxtisas: "İqtisadçı",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    Ölkəsi: "Azərbaycan, Şəki",
    img: "/candidates/img103.jpg",
    canId: 86,
    vote: 4169,
  },
  {
    idn: 105,
    Adı: "Şərifov Fariz Məhəmmədismail oğlu",
    Təvəllüd: "12/22/1957",
    DogYer: "Ağdaş",
    Təhsil: "Ali",
    İxtisas: "İdamançı",
    Fəaliyyət: "Təqaüdçü",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "Yoxdur",
    Ölkəsi: "Azərbaycan, Ağdaş",
    img: "/candidates/img105.jpg",
    canId: 147,
    vote: 2265,
  },
  {
    idn: 117,
    Adı: "Rəfiyeva Röya Tahir qızı",
    Təvəllüd: "7/3/1981",
    DogYer: "Oguz",
    Təhsil: "Ali",
    İxtisas: "Pedaqoq",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    PartiaÜzvi: "Yox",
    Ölkəsi: "Almaniya",
    img: "/candidates/img117.jpg",
    canId: 136,
    vote: 3677,
  },
  {
    idn: 119,
    Adı: "Həsrətli Nüsrət Həsrət oğlu",
    Təvəllüd: "10/10/1954",
    DogYer: "Agdaş",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "Həkim",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "Evli",
    PartiaÜzvi: "AMMN",
    Ölkəsi: "Azərbaican, Agdaş",
    img: "/candidates/img119.jpg",
    canId: 71,
    vote: 2988,
  },
  {
    idn: 122,
    Adı: "Abasov Səid Əzizxan oğlu",
    Təvəllüd: "3/5/1980",
    DogYer: "Sabirabad",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaijan",
    img: "/candidates/img122.jpg",
    canId: 1,
    vote: 3655,
  },
  {
    idn: 124,
    Adı: "Məmmədli Şükür Malik oğlu",
    Təvəllüd: "10/18/1954",
    DogYer: "İsmayıllı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaijan, İsmayıllı",
    img: "/candidates/img124.jpg",
    canId: 97,
    vote: 2807,
  },
  {
    idn: 125,
    Adı: "Məmmədov Şakir Məhəmmədəli oğlu",
    Təvəllüd: "7/5/1955",
    DogYer: "Goy-göl",
    Təhsil: "Orta-texniki",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaijan, Sumqaıt",
    img: "/candidates/img162.jpg",
    canId: 101,
    vote: 2513,
  },
  {
    idn: 128,
    Adı: "Şirinli Şahin Salam oğlu",
    Təvəllüd: "8/30/1953",
    DogYer: "İsnmayıllı",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Belçika",
    img: "/candidates/img128.jpg",
    canId: 153,
    vote: 2566,
  },
  {
    idn: 135,
    Adı: "İsgəndərov Ruslan Telman oğlu",
    Təvəllüd: "10/22/1985",
    DogYer: "",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Rusiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya",
    img: "/candidates/img135.jpg",
    canId: 80,
    vote: 4155,
  },
  {
    idn: 138,
    Adı: "Zeynallı Əvəz Tapdıq oğlu",
    Təvəllüd: "1/1/1970",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img138.jpg",
    canId: 174,
    vote: 7442,
  },
  {
    idn: 139,
    Adı: "Manafov Mirzə Tavar oğlu",
    Təvəllüd: "2/21/1968",
    DogYer: "Yardımlı",
    Təhsil: "Ali",
    İxtisas: "Hüquq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img139.jpg",
    canId: 91,
    vote: 2581,
  },
  {
    idn: 141,
    Adı: "Xəlilov Famil Malik oğlu",
    Təvəllüd: "7/14/1990",
    DogYer: "Bakı",
    Təhsil: "",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AXCP",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img141.jpg",
    canId: 169,
    vote: 3978,
  },
  {
    idn: 142,
    Adı: "İsayev Elvin İltiham oğlu",
    Təvəllüd: "10/21/1980",
    DogYer: "Masallı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya, S-Pb",
    img: "/candidates/img142.jpg",
    canId: 79,
    vote: 5140,
  },
  {
    idn: 143,
    Adı: "Qafarova Xuraman Əşrəf qızı",
    Təvəllüd: "7/6/1958",
    DogYer: "Göyçay",
    Təhsil: "Ali",
    İxtisas: "Filoloq",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img143.jpg",
    canId: 124,
    vote: 3172,
  },
  {
    idn: 144,
    Adı: "Oruclu Ərəstun Məmməd oğlu",
    Təvəllüd: "8/18/1963",
    DogYer: "Gəncə",
    Təhsil: "Ali",
    İxtisas: "Həkim",
    Fəaliyyət: "Siyasətçi",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "ABŞ",
    img: "/candidates/img144.jpg",
    canId: 119,
    vote: 6947,
  },
  {
    idn: 149,
    Adı: "Cabbarov Səxavət Ağaşirin oğlu",
    Təvəllüd: "6/15/1978",
    DogYer: "Agdaş",
    Təhsil: "Ali",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Agdaş",
    img: "/candidates/img149.jpg",
    canId: 25,
    vote: 2759,
  },
  {
    idn: 152,
    Adı: "Cəfərova Arifə Arif qızı",
    Təvəllüd: "11/2/1975",
    DogYer: "Bakı",
    Təhsil: "Ali",
    İxtisas: "İnşatçı",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img152.jpg",
    canId: 33,
    vote: 4049,
  },
  {
    idn: 156,
    Adı: "Əliyev Ruslan Rasim oğlu",
    Təvəllüd: "11/12/2001",
    DogYer: "Russiya",
    Təhsil: "Ali",
    İxtisas: "Aviasiya",
    Fəaliyyət: "",
    Vətəndaşlıq: "Russiya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Fransa",
    img: "/candidates/img156.jpg",
    canId: 50,
    vote: 4572,
  },
  {
    idn: 157,
    Adı: "Emçiyev Rəfail Nizami oğlu",
    Təvəllüd: "3/8/1987",
    DogYer: "Balakən",
    Təhsil: "Orta",
    İxtisas: "Hərbi",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan",
    img: "/candidates/img157.jpg",
    canId: 52,
    vote: 3717,
  },
  {
    idn: 164,
    Adı: "Miriyeva Dilarə Qəzənfər qızı",
    Təvəllüd: "7/1/1959",
    DogYer: "Tovus",
    Təhsil: "Ali",
    İxtisas: "Juranlist",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "AMMH",
    Ölkəsi: "Azərbaycan, Bakı",
    img: "/candidates/img164.jpg",
    canId: 106,
    vote: 3979,
  },
  {
    idn: 165,
    Adı: "Namazova Firuzə Şahin qızı",
    Təvəllüd: "7/21/1995",
    DogYer: "Qəbələ",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan, Beylaqan",
    img: "/candidates/img165.jpg",
    canId: 115,
    vote: 2653,
  },
  {
    idn: 167,
    Adı: "Qasımov Məcid Kamal oğlu",
    Təvəllüd: "1/31/1987",
    DogYer: "Qazax",
    Təhsil: "Orta",
    İxtisas: "Hərbi",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Azərbaycan,Şəmkir",
    img: "/candidates/img167.jpg",
    canId: 126,
    vote: 3284,
  },
  {
    idn: 173,
    Adı: "Xanlarova Rəbiyyə Əli qızı",
    Təvəllüd: "6/6/1960",
    DogYer: "Bakı",
    Təhsil: "Orta",
    İxtisas: "",
    Fəaliyyət: "",
    Vətəndaşlıq: "Avstriya",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Avstriya",
    img: "/candidates/img173.jpg",
    canId: 166,
    vote: 2466,
  },
  {
    idn: 178,
    Adı: "Abdullayeva Sənubər Məhəmməd qızı",
    Təvəllüd: "2/28/1951",
    DogYer: "Ermənistan",
    Təhsil: "Ali",
    İxtisas: "İdman",
    Fəaliyyət: "",
    Vətəndaşlıq: "Azərbaycan",
    AzVətOlubmu: "Var",
    AiləStatus: "",
    PartiaÜzvi: "",
    Ölkəsi: "Rusiya",
    img: "/candidates/img178.jpg",
    canId: 8,
    vote: 3205,
  },
];
