export const ebooks = [
  {
    id: 1,
    titleAz: "Andaluniya",
    titleEn: "Andaluniya",
    author: "Abid Gafarov",
    year: "2022",
    imgUrl: "/ebooks/andaluniya.jpg",
    pdfUrl: "/ebooks/andaluniya.pdf",
    qr: "/ebooks/qr/abidqafar.jpg",
  },
  {
    id: 2,
    titleAz: "Mələyin Ölümü",
    titleEn: "Death of Angel",
    author: "Abid Gafarov",
    year: "2024",
    imgUrl: "/ebooks/angeldeath.jpg",
    pdfUrl: "/ebooks/deathofangel.pdf",
    qr: "/ebooks/qr/abidqafar.jpg",
  },
  {
    id: 3,
    titleAz: "Tiran-Qanlı Qayıdiş",
    titleEn: "Bloody tyrant returns",
    author: "İsa Sadıqov",
    year: "2020",
    imgUrl: "/ebooks/tiran.jpg",
    pdfUrl: "/ebooks/tiran.pdf",
    qr: "/ebooks/qr/isasadig.jpg",
  },
  {
    id: 4,
    titleAz: "Demokratiya dərsləri",
    titleEn: "Democracy Lessons",
    author: "Ataxan Əbilov",
    year: "2018",
    imgUrl: "/ebooks/democracylessens.jpg",
    pdfUrl: "/ebooks/democrascylessons2018.pdf",
    qr: "/ebooks/qr/ataxan.jpg",
  },
  {
    id: 5,
    titleAz: "Azərbaycan Avropa ailəsində",
    titleEn: "Azerbaijan in the European family",
    author: "Ataxan Əbilov",
    year: "2018",
    imgUrl: "/ebooks/azevrope.jpg",
    pdfUrl: "/ebooks/azerbaijanevropafamily.pdf",
    qr: "/ebooks/qr/ataxan.jpg",
  },
  {
    id: 6,
    titleAz: "Qaçaq Şamil",
    titleEn: "Fugitive Shamil",
    author: "Sahib Camal",
    year: "2021",
    imgUrl: "/ebooks/shamil.jpg",
    pdfUrl: "/ebooks/fugitive.pdf",
    qr: "/ebooks/qr/azxpqr.jpg",
  },
];
