export const politicsList = [
  {
    id: 1,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 2,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 3,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 4,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 5,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 6,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 7,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 8,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 9,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 10,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 11,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 12,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 13,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 14,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 15,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 16,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 17,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 18,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 19,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 20,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 21,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 22,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 23,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
  {
    id: 24,
    name: "Goyan Front",
    since: "2022",
    img: "/pol.jpg",
    work: "Zural TZ",
  },
  {
    id: 25,
    name: "Basan Daldan",
    since: "2023",
    img: "/pol.jpg",
    work: "Zural TV",
  },
];
