export const tartarData = [
  // {
  //   personal: {
  //     first: "Adil",
  //     last: "Sabirli",
  //     title: "Baş leytenant",
  //     year: "2017",
  //     base: "Barda base",
  //     dob: "--/--/----",
  //     status: "QY",
  //   },
  //   img: "/images/tartar/e_guliyev.png",
  //   accusation: "Vətən xaini",
  //   judgment: "Bəyanət alıb qətildən sonra",
  //   url: [
  //     "https://www.meydan.tv/az/article/terter-isine-gore-oldurulen-elcin-quliyev-beraet-aldi/",
  //     "https://report.az/hadise/terter-isi-nde-olen-herbciye-beraet-verilib/",
  //     "https://www.google.com/search?q=el%C3%A7in+quliyev-T%C9%99rt%C9%99r+q%C9%99tlam%C4%B1%C2%A0&sca_esv=39f9327b471b4a1c&sca_upv=1&rlz=1CDGOYI_enRU823RU824&hl=ru&sxsrf=ADLYWIIVaQ0gGiG3el-JRD6U5SKEpDbaAQ%3A1727764724247&ei=9Jj7ZvjUDsj97_UPiP3SuAw&oq=el%C3%A7in+quliyev-T%C9%99rt%C9%99r+q%C9%99tlam%C4%B1%C2%A0&gs_lp=EhNtb2JpbGUtZ3dzLXdpei1zZXJwIiNlbMOnaW4gcXVsaXlldi1UyZlydMmZciBxyZl0bGFtxLHCoDIIEAAYgAQYogQyCBAAGIAEGKIEMggQABiABBiiBEjHiwJQ0Q9Yg-YBcAd4AZABAJgBmQWgAcUlqgEKMC40LjE1LjUtMbgBA8gBAPgBAZgCG6AC2ybCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICDRAuGIAEGLADGEMYigXCAhMQLhiABBiwAxhDGMgDGIoF2AEBwgIKEAAYgAQYFBiHAsICCBAuGIAEGMsBwgIIEAAYgAQYywHCAgUQABiABMICBhAAGBYYHsICBRAhGKABwgIFECEYnwWYAwCIBgGQBhG6BgQIARgIkgcKNy4zLjE2LjUtMaAHojc&sclient=mobile-gws-wiz-serp#fpstate=ive&vld=cid:cad60b71,vid:4acFkPEbSJE,st:0",
  //   ],
  // },
  {
    personal: {
      first: "Elchin",
      last: "Quliyev",
      title: "MAXE",
      year: "2017",
      base: "Barda base",
      dob: "--/--/----",
      status: "QY",
    },
    img: "/images/tartar/e_guliyev.png",
    accusation: "Vətən xaini",
    judgment: "Bəyanət alıb qətildən sonra",
    url: [
      "https://www.meydan.tv/az/article/terter-isine-gore-oldurulen-elcin-quliyev-beraet-aldi/",
      "https://report.az/hadise/terter-isi-nde-olen-herbciye-beraet-verilib/",
      "https://www.google.com/search?q=el%C3%A7in+quliyev-T%C9%99rt%C9%99r+q%C9%99tlam%C4%B1%C2%A0&sca_esv=39f9327b471b4a1c&sca_upv=1&rlz=1CDGOYI_enRU823RU824&hl=ru&sxsrf=ADLYWIIVaQ0gGiG3el-JRD6U5SKEpDbaAQ%3A1727764724247&ei=9Jj7ZvjUDsj97_UPiP3SuAw&oq=el%C3%A7in+quliyev-T%C9%99rt%C9%99r+q%C9%99tlam%C4%B1%C2%A0&gs_lp=EhNtb2JpbGUtZ3dzLXdpei1zZXJwIiNlbMOnaW4gcXVsaXlldi1UyZlydMmZciBxyZl0bGFtxLHCoDIIEAAYgAQYogQyCBAAGIAEGKIEMggQABiABBiiBEjHiwJQ0Q9Yg-YBcAd4AZABAJgBmQWgAcUlqgEKMC40LjE1LjUtMbgBA8gBAPgBAZgCG6AC2ybCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICDRAuGIAEGLADGEMYigXCAhMQLhiABBiwAxhDGMgDGIoF2AEBwgIKEAAYgAQYFBiHAsICCBAuGIAEGMsBwgIIEAAYgAQYywHCAgUQABiABMICBhAAGBYYHsICBRAhGKABwgIFECEYnwWYAwCIBgGQBhG6BgQIARgIkgcKNy4zLjE2LjUtMaAHojc&sclient=mobile-gws-wiz-serp#fpstate=ive&vld=cid:cad60b71,vid:4acFkPEbSJE,st:0",
    ],
  },
  {
    personal: {
      first: "Saleh",
      last: "Qafarov",
      title: "Leytenant",
      year: "2017",
      base: "Barda base",
      dob: "--/--/----",
      status: "QY",
    },
    img: "/images/tartar/s_gafarov.png",
    accusation: "Vətən xaini",
    judgment: "Bəyanət alıb qətildən sonra",
    url: [
      "https://youtu.be/lDSeijkS3hE?si=tEHLg1gw2qAJVDfZ",
      "https://youtu.be/erOBeJOH8Tw?si=HLOiqXpiS-GkIhW4",
    ],
  },
  {
    personal: {
      first: "Süleyman",
      last: "Kazımov",
      title: "Kapitan",
      year: "2017",
      base: "Barda base",
      dob: "--/--/----",
      status: "QY",
    },
    img: "/images/tartar/slm_kazımov.png",
    accusation: "Vətən xaini",
    judgment: "Bəyanət alıb qətildən sonra",
    url: ["https://www.youtube.com/watch?v=_WN8kyKwnrY"],
  },
  {
    personal: {
      first: "Elçin",
      last: "Mirzəliyev",
      title: "Leytenant",
      year: "2017",
      base: "Barda base",
      dob: "--/--/----",
      status: "QY",
    },
    img: "/images/tartar/e_mirzəliyev.png",
    accusation: "Vətən xaini",
    judgment: "Bəyanət alıb qətildən sonra",
    url: ["https://www.youtube.com/watch?v=6BOP57zLpWA"],
  },
  {
    personal: {
      first: "Ruslan",
      last: "Ocaqverdiyev",
      title: "Gizir",
      year: "2017",
      base: "Barda base",
      dob: "--/--/----",
      status: "QY",
    },
    img: "/images/tartar/r_ocaq.png",
    accusation: "Vətən xaini",
    judgment: "Bəyanət alıb qətildən sonra",
    url: ["https://www.youtube.com/watch?v=GpBYit4JJq0"],
  },
  {
    personal: {
      first: "Səxavət",
      last: "Bünyatov",
      title: "Gizir",
      year: "2017",
      base: "Barda base",
      dob: "--/--/----",
      status: "QY",
    },
    img: "/images/tartar/b_bunyatov.png",
    accusation: "Vətən xaini",
    judgment: "Bəyanət alıb qətildən sonra",
    url: ["https://www.youtube.com/watch?v=l3inhcJwanQ"],
  },
  {
    personal: {
      first: "Mehman",
      last: "Hüseyinov",
      title: "MAXE",
      year: "2017",
      base: "Barda base",
      dob: "--/--/----",
      status: "QY",
    },
    img: "/images/tartar/m_husinov.png",
    accusation: "Vətən xaini",
    judgment: "Bəyanət alıb qətildən sonra",
    url: ["https://www.youtube.com/watch?v=EpcveSIR24Q"],
  },
];
